dat_format.py文件验证

In [8]:
# 验证dat文件的读取
import numpy as np
file_path = 'D:\\Code\\PIV_data\\flow2\\PIVlab_0016.dat'
data_np_void = np.genfromtxt(fname=file_path,
                             skip_header=6,
                             skip_footer=-1,
                             names=["x", "y", "u", "v", "isNaN", "vorticity", "magnitude", "divergence",
                                                "dcev",
                                                "simple_shear", "simple_strain", "vector_direction"],
                              dtype=np.float64,
                              delimiter=' ')
# print(data_np_void)
data_np = np.array(data_np_void.tolist(), dtype=np.float64)
# # 不使用科学计数法打印data_np
# np.set_printoptions(suppress=True)
# # 在jupyter中不省略打印
# np.set_printoptions(threshold=np.inf)
print(data_np[0,0])

0.002681580838


In [15]:
# 验证dat数据转换是否正确
import numpy as np
arr = np.load('D:\\Code\\PIV_dataset\\dataset\\PIV-1_0104.npy')
# 不使用科学计数法打印data_np
np.set_printoptions(suppress=True)
# 在jupyter中不省略打印
np.set_printoptions(threshold=np.inf)
print(arr[0, :, :])
print(arr[1, -1, 0])

[[-0.09060122  0.07274267 -0.10592677 -0.06851245  0.10881512  0.11168005
   0.03882908  0.22225045  0.33898577  0.49299914  0.61451983  0.56193179
   0.45513478  0.46873015  0.23236543  0.04045574 -0.17114304  0.15437877
   0.07292612 -0.02368993  0.10003761  0.10721708]
 [-0.01584987 -0.06038145 -0.18660615 -0.04551266 -0.01916685  0.02004565
   0.19674475  0.34628141  0.46018237  0.60483038  0.33282539  0.27073124
   0.56328195  0.2584509   0.06582934  0.16246511 -0.27549204 -0.17928861
  -0.04424643 -0.1854174  -0.20601808  0.06118012]
 [ 0.04039534 -0.10652293 -0.09643015 -0.24241379 -0.28539437  0.03790397
   0.44098172  0.4160099   0.57300758  0.68292683  0.48937514  0.53566962
   0.37172303 -0.01571914 -0.06947476 -0.15173621 -0.21781325 -0.07615001
  -0.01644919  0.08526981  0.11862461  0.06111605]
 [-0.11849087 -0.32435    -0.24021703 -0.25912243 -0.06336082  0.15793483
   0.17121443  0.14780036  0.73291129  0.85092634  0.68505532  0.53614676
   0.25768888 -0.01673816  0.0244

In [9]:
# 验证划分数据集后的数据还是否正确
import numpy as np
arr = np.load('D:\\Code\\PIV_dataset\\train_dataset\\PIV-2_0016.npy')
# 不使用科学计数法打印data_np
np.set_printoptions(suppress=True)
# 在jupyter中不省略打印
np.set_printoptions(threshold=np.inf)
print(arr[1, :, :])
print(arr[1, -1, 0])
print(type(arr))

[[-0.05358093  0.38246974 -0.24815643 -0.06962842 -0.0542121   0.01033876
   0.17857337  0.44188443  0.31632751  0.27030233  0.31270283  0.33293188
   0.42721918  0.21519506  0.09486751  0.38906345  0.51115757  0.95607334
   1.0577091   0.62125319  0.82493645  0.84975028]
 [-0.06813214  0.18200028  0.0228037   0.17193151  0.27969494  0.32272798
   0.68412155  0.77561116  0.65092242  0.4224197   0.58878094  0.521492
   0.37365401  0.11219703  0.02372115  0.20464458  0.28232703  0.54061991
   0.81197417  0.75828177  0.84568501  0.79603386]
 [-0.07730904  0.12922898  0.1377856   0.14087023  0.53553736  0.39491758
   0.35505855  0.56958026  0.60684758  0.32843527  0.14743993  0.24794589
   0.30319032  0.0884638   0.04256321  0.17446776  0.18287836  0.75776911
   1.42075109  0.95917577  0.79963827  0.58112669]
 [ 0.07600705  0.41325036  0.63072443  0.43132424  0.81079525  1.06585669
   1.00748789  0.54156238  0.67821831  0.72007263  0.40556818  0.4248054
   0.32181361 -0.08626445 -0.1052575

In [12]:
# 验证划分数据集后的数据还是否正确
import numpy as np
arr = np.load('D:\\Code\\PIV_dataset\\test_dataset\\PIV-2_0069.npy')
# 不使用科学计数法打印data_np
np.set_printoptions(suppress=True)
# 在jupyter中不省略打印
np.set_printoptions(threshold=np.inf)
print(arr[2, :, :])
print(arr[1, -1, 0])
print(type(arr))

[[ 118.6704788   149.5453033  -134.8123474  -106.2008591   103.7584763
    81.46971893   81.22963715   78.61493683   47.22558975   30.82381439
    54.7133255    74.67062378   64.24308777   54.68333054   55.20491409
   -21.13389015   71.19075775   77.71248627   85.42002106   90.45965576
    84.94828033   76.05027771]
 [-119.1279221  -149.6785431  -153.8415985   165.4881744   115.0980606
   103.9393082    80.11431885   60.32209396   63.57466888   35.92221832
    35.29698563   42.02239227   46.5942955    74.68925476 -172.0904999
   131.4344635    29.47842407   84.02385712  102.3441086    93.59370422
    87.08187866   71.10505676]
 [-120.7492752  -155.2164764    99.17023468  114.7596893   141.6995392
   112.6035919    91.22883606   69.17551422   67.83480835   74.76818085
    59.28551483   48.09336853   46.54303741   43.24930573  142.6895905
    98.00902557  115.0073395    85.67216492   99.10541534   88.74300385
    83.29912567   77.89491272]
 [ -62.76002502  177.9933777   123.0606003    91

In [17]:
# 验证划分数据集后的数据还是否正确
import numpy as np
arr = np.load('D:\\Code\\PIV_dataset\\validate_dataset\\PIV-1_0104.npy')
# 不使用科学计数法打印data_np
np.set_printoptions(suppress=True)
# 在jupyter中不省略打印
np.set_printoptions(threshold=np.inf)
print(arr[0, :, :])
print(arr[1, -1, 0])
print(type(arr))

[[-0.09060122  0.07274267 -0.10592677 -0.06851245  0.10881512  0.11168005
   0.03882908  0.22225045  0.33898577  0.49299914  0.61451983  0.56193179
   0.45513478  0.46873015  0.23236543  0.04045574 -0.17114304  0.15437877
   0.07292612 -0.02368993  0.10003761  0.10721708]
 [-0.01584987 -0.06038145 -0.18660615 -0.04551266 -0.01916685  0.02004565
   0.19674475  0.34628141  0.46018237  0.60483038  0.33282539  0.27073124
   0.56328195  0.2584509   0.06582934  0.16246511 -0.27549204 -0.17928861
  -0.04424643 -0.1854174  -0.20601808  0.06118012]
 [ 0.04039534 -0.10652293 -0.09643015 -0.24241379 -0.28539437  0.03790397
   0.44098172  0.4160099   0.57300758  0.68292683  0.48937514  0.53566962
   0.37172303 -0.01571914 -0.06947476 -0.15173621 -0.21781325 -0.07615001
  -0.01644919  0.08526981  0.11862461  0.06111605]
 [-0.11849087 -0.32435    -0.24021703 -0.25912243 -0.06336082  0.15793483
   0.17121443  0.14780036  0.73291129  0.85092634  0.68505532  0.53614676
   0.25768888 -0.01673816  0.0244

In [1]:
# 验证裁剪后数据集的数据还是否正确
import numpy as np
# arr = np.load('D:\\Code\\PIV_dataset\\train\\PIV-2_00016.npy').astype(np.float32)
arr = np.load('D:\\Code\\PIV_dataset\\train\\PIV-2_0016.npy')

# 不使用科学计数法打印data_np
np.set_printoptions(suppress=True)
# 在jupyter中不省略打印
np.set_printoptions(threshold=np.inf)
print(arr[1, :, :])
print(arr[1, -1, 0])
print(arr.shape)
print(type(arr))

[[-0.24815643 -0.06962842 -0.0542121   0.01033876  0.17857337  0.44188443
   0.31632751  0.27030233  0.31270283  0.33293188  0.42721918  0.21519506
   0.09486751  0.38906345  0.51115757  0.95607334  1.0577091   0.62125319
   0.82493645  0.84975028]
 [ 0.0228037   0.17193151  0.27969494  0.32272798  0.68412155  0.77561116
   0.65092242  0.4224197   0.58878094  0.521492    0.37365401  0.11219703
   0.02372115  0.20464458  0.28232703  0.54061991  0.81197417  0.75828177
   0.84568501  0.79603386]
 [ 0.1377856   0.14087023  0.53553736  0.39491758  0.35505855  0.56958026
   0.60684758  0.32843527  0.14743993  0.24794589  0.30319032  0.0884638
   0.04256321  0.17446776  0.18287836  0.75776911  1.42075109  0.95917577
   0.79963827  0.58112669]
 [ 0.63072443  0.43132424  0.81079525  1.06585669  1.00748789  0.54156238
   0.67821831  0.72007263  0.40556818  0.4248054   0.32181361 -0.08626445
  -0.10525755  0.12400405  0.69889551  1.22444058  1.46734011  0.85803217
   0.48345923  0.55477107]
 [ 0.

In [2]:
# 验证裁剪后数据集的数据还是否正确
import numpy as np
# arr = np.load('D:\\Code\\PIV_dataset\\train\\PIV-2_00016.npy').astype(np.float32)
arr = np.load('D:\\Code\\PIV_dataset\\test\\PIV-2_0069.npy')

# 不使用科学计数法打印data_np
np.set_printoptions(suppress=True)
# 在jupyter中不省略打印
np.set_printoptions(threshold=np.inf)
print(arr[2, :, :])
print(arr[1, -1, 0])
print(arr.shape)
print(type(arr))

[[-134.8123474  -106.2008591   103.7584763    81.46971893   81.22963715
    78.61493683   47.22558975   30.82381439   54.7133255    74.67062378
    64.24308777   54.68333054   55.20491409  -21.13389015   71.19075775
    77.71248627   85.42002106   90.45965576   84.94828033   76.05027771]
 [-153.8415985   165.4881744   115.0980606   103.9393082    80.11431885
    60.32209396   63.57466888   35.92221832   35.29698563   42.02239227
    46.5942955    74.68925476 -172.0904999   131.4344635    29.47842407
    84.02385712  102.3441086    93.59370422   87.08187866   71.10505676]
 [  99.17023468  114.7596893   141.6995392   112.6035919    91.22883606
    69.17551422   67.83480835   74.76818085   59.28551483   48.09336853
    46.54303741   43.24930573  142.6895905    98.00902557  115.0073395
    85.67216492   99.10541534   88.74300385   83.29912567   77.89491272]
 [ 123.0606003    91.72948456   44.97584152   74.56340027   85.36152649
    79.25310516   87.7698822    63.06537628   66.97827148   41

In [3]:
# 验证裁剪后数据集的数据还是否正确
import numpy as np
# arr = np.load('D:\\Code\\PIV_dataset\\train\\PIV-2_00016.npy').astype(np.float32)
arr = np.load('D:\\Code\\PIV_dataset\\validate\\PIV-1_0104.npy')

# 不使用科学计数法打印data_np
np.set_printoptions(suppress=True)
# 在jupyter中不省略打印
np.set_printoptions(threshold=np.inf)
print(arr[0, :, :])
print(arr[1, -1, 0])
print(arr.shape)
print(type(arr))

[[-0.10592677 -0.06851245  0.10881512  0.11168005  0.03882908  0.22225045
   0.33898577  0.49299914  0.61451983  0.56193179  0.45513478  0.46873015
   0.23236543  0.04045574 -0.17114304  0.15437877  0.07292612 -0.02368993
   0.10003761  0.10721708]
 [-0.18660615 -0.04551266 -0.01916685  0.02004565  0.19674475  0.34628141
   0.46018237  0.60483038  0.33282539  0.27073124  0.56328195  0.2584509
   0.06582934  0.16246511 -0.27549204 -0.17928861 -0.04424643 -0.1854174
  -0.20601808  0.06118012]
 [-0.09643015 -0.24241379 -0.28539437  0.03790397  0.44098172  0.4160099
   0.57300758  0.68292683  0.48937514  0.53566962  0.37172303 -0.01571914
  -0.06947476 -0.15173621 -0.21781325 -0.07615001 -0.01644919  0.08526981
   0.11862461  0.06111605]
 [-0.24021703 -0.25912243 -0.06336082  0.15793483  0.17121443  0.14780036
   0.73291129  0.85092634  0.68505532  0.53614676  0.25768888 -0.01673816
   0.02441759 -0.19062157 -0.22978437 -0.26394615 -0.2637023   0.29605976
   0.45442685  0.15490793]
 [-0.13

In [1]:
# 验证GT-LR数据对的匹配
# 验证裁剪后数据集的数据还是否正确
import numpy as np

arr = np.load('D:\\Code\\PIV_dataset\\test_lr_gt\\PIV-2_0069.npy')

# 不使用科学计数法打印data_np
np.set_printoptions(suppress=True)
# 在jupyter中不省略打印
np.set_printoptions(threshold=np.inf)
print(arr[2, :, :])
print(arr[1, -1, 0])
print(arr.shape)
print(type(arr))

[[-134.8123474  -106.2008591   103.7584763    81.46971893   81.22963715
    78.61493683   47.22558975   30.82381439   54.7133255    74.67062378
    64.24308777   54.68333054   55.20491409  -21.13389015   71.19075775
    77.71248627   85.42002106   90.45965576   84.94828033   76.05027771]
 [-153.8415985   165.4881744   115.0980606   103.9393082    80.11431885
    60.32209396   63.57466888   35.92221832   35.29698563   42.02239227
    46.5942955    74.68925476 -172.0904999   131.4344635    29.47842407
    84.02385712  102.3441086    93.59370422   87.08187866   71.10505676]
 [  99.17023468  114.7596893   141.6995392   112.6035919    91.22883606
    69.17551422   67.83480835   74.76818085   59.28551483   48.09336853
    46.54303741   43.24930573  142.6895905    98.00902557  115.0073395
    85.67216492   99.10541534   88.74300385   83.29912567   77.89491272]
 [ 123.0606003    91.72948456   44.97584152   74.56340027   85.36152649
    79.25310516   87.7698822    63.06537628   66.97827148   41

In [9]:
# 验证GT-LR数据对的匹配，最后一行第一个-79.22972141 没问题了
# 验证裁剪后数据集的数据还是否正确
import numpy as np

arr = np.load('D:\\Code\\PIV_dataset\\test_lr\\PIV-2_0069.npy')

# 不使用科学计数法打印data_np
np.set_printoptions(suppress=True)
# 在jupyter中不省略打印
np.set_printoptions(threshold=np.inf)
print(arr[2, :, :])
print(arr[1, -1, 0])
print(arr.shape)
print(type(arr))

[[  61.0913322    68.51778173   55.74381232   44.65504229   88.51788282]
 [  46.70456195   57.51133388   -0.3735429    75.6928897   100.26277923]
 [  59.24312711   63.80058306  -98.33003259   23.22656821   95.86703062]
 [  76.52111077   -0.54697107 -104.96462917   90.58747029   91.03678989]
 [  85.53063082  -82.94271232  -82.89229583   47.05281925  106.46801758]
 [  92.45121861 -102.77919531  -77.0276754    49.10493982   91.15527582]
 [  66.33632195  -89.70726269  -60.09188664   57.93022799   89.97481966]
 [  43.58294428  -94.75369572  -67.39368642   82.31736755   89.32512212]
 [  18.56342363 -100.02275038  -54.30402256   33.1366952   101.69312955]
 [  66.18812835  -68.0079771   -40.60436159   20.78178788   82.81258559]
 [ -79.22972141  -85.03303898  -36.12771703    3.5706947    56.90132814]]
-0.0414864730020625
(3, 11, 5)
<class 'numpy.ndarray'>


In [10]:
# 验证GT-LR数据对的匹配，最后一行第一个-79.22972141 没问题了
# 验证裁剪后数据集的数据还是否正确
import numpy as np

arr = np.load('D:\\Code\\PIV_dataset\\validate_lr_gt\\PIV-2_0132.npy')

# 不使用科学计数法打印data_np
np.set_printoptions(suppress=True)
# 在jupyter中不省略打印
np.set_printoptions(threshold=np.inf)
print(arr[2, :, :])
print(arr[1, -1, 0])
print(arr.shape)
print(type(arr))

[[0.05253104 0.98785251 0.04374734 0.03319402 0.75454678 0.64700961
  0.68286053 0.67645209 0.68026226 0.7133849  0.69150642 0.65105411
  0.55071634 0.76454417 0.74789365 0.80185489 0.82811472 0.71021759
  0.76268199 0.70612371]
 [0.99851696 0.81528134 0.85114041 0.73340378 0.69370716 0.68753985
  0.71147741 0.66274477 0.65087753 0.64724944 0.65502934 0.57585718
  0.56052319 0.7963623  0.83388924 0.89929988 0.84142184 0.7330971
  0.73080008 0.81092208]
 [0.03401444 0.76367772 0.47914262 0.69131395 0.75571755 0.69423202
  0.69427954 0.69236861 0.67822348 0.66365673 0.6348658  0.6030956
  0.74427921 0.90785941 0.88411706 0.86548737 0.79845201 0.73832677
  0.72836716 0.60135542]
 [0.36255312 0.49413516 0.54929344 0.60485358 0.69619461 0.67306064
  0.68662611 0.67402985 0.64343793 0.6661402  0.65834462 0.64368357
  0.80330214 0.88046382 0.87880844 0.80847156 0.80426718 0.78780292
  0.7653268  0.79297571]
 [0.67235103 0.59848707 0.62296982 0.572953   0.68000582 0.69189652
  0.66308295 0.611

In [21]:
# 验证布尔运算
gou = True
if not gou:
    print('True')
else:
    print('False')

False


In [1]:
# 验证布尔运算
gou = False
if gou:
    print('======')
else:
    print('*****8')

*****8


In [1]:
# 验证文件索引
import os  
import re  
  
# 假设 args.raw_dataset_dir 是包含这些文件的文件夹路径  
flow_files = os.listdir(f"D:\\Code\\PIV_dataset\\dataset")  
  
# 使用正则表达式匹配文件名，并提取数字部分  
def extract_number(filename):  
    match = re.search(r'PIV-1_(\d+)\.npy', filename)  
    return int(match.group(1)) if match else None  
  
# 过滤出PIV-1_xxx.npy的文件，并按数字排序  
piv1_files = sorted((filename for filename in flow_files if re.match(r'PIV-1_\d+\.npy', filename)), key=extract_number)  
  
# 检查我们是否确实获得了PIV-1_00001.npy到PIV-1_00180.npy之间的所有文件  
assert all(f.startswith('PIV-1_') and 1 <= int(f.split('_')[1].split('.')[0]) <= 180 for f in piv1_files), "Not all PIV-1 files are present or the range is incorrect."  
  
# 输出排序后的文件名列表  
for filename in piv1_files:  
    print(filename)

PIV-1_00001.npy
PIV-1_00002.npy
PIV-1_00003.npy
PIV-1_00004.npy
PIV-1_00005.npy
PIV-1_00006.npy
PIV-1_00007.npy
PIV-1_00008.npy
PIV-1_00009.npy
PIV-1_00010.npy
PIV-1_00011.npy
PIV-1_00012.npy
PIV-1_00013.npy
PIV-1_00014.npy
PIV-1_00015.npy
PIV-1_00016.npy
PIV-1_00017.npy
PIV-1_00018.npy
PIV-1_00019.npy
PIV-1_00020.npy
PIV-1_00021.npy
PIV-1_00022.npy
PIV-1_00023.npy
PIV-1_00024.npy
PIV-1_00025.npy
PIV-1_00026.npy
PIV-1_00027.npy
PIV-1_00028.npy
PIV-1_00029.npy
PIV-1_00030.npy
PIV-1_00031.npy
PIV-1_00032.npy
PIV-1_00033.npy
PIV-1_00034.npy
PIV-1_00035.npy
PIV-1_00036.npy
PIV-1_00037.npy
PIV-1_00038.npy
PIV-1_00039.npy
PIV-1_00040.npy
PIV-1_00041.npy
PIV-1_00042.npy
PIV-1_00043.npy
PIV-1_00044.npy
PIV-1_00045.npy
PIV-1_00046.npy
PIV-1_00047.npy
PIV-1_00048.npy
PIV-1_00049.npy
PIV-1_00050.npy
PIV-1_00051.npy
PIV-1_00052.npy
PIV-1_00053.npy
PIV-1_00054.npy
PIV-1_00055.npy
PIV-1_00056.npy
PIV-1_00057.npy
PIV-1_00058.npy
PIV-1_00059.npy
PIV-1_00060.npy
PIV-1_00061.npy
PIV-1_00062.npy
PIV-1_00

In [13]:
re.match(r'PIV-1_\d+\.npy', 'PIV-1_00179.npy')

<re.Match object; span=(0, 15), match='PIV-1_00179.npy'>

In [12]:
import os
import re

flow_files = os.listdir(f"D:\\Code\\PIV_dataset\\dataset")

# 过滤出以PIV-1开头的文件名
piv1_files = [file for file in flow_files if file.startswith("PIV-1")]

# 提取文件名中的数字并按照从小到大的顺序排序
sorted_piv1_files = sorted(piv1_files, key=lambda x: int(re.findall(r'\d+', x)[1]))

# print(sorted_piv1_files)
for filename in sorted_piv1_files:  
    print(filename)

PIV-1_00001.npy
PIV-1_00002.npy
PIV-1_00003.npy
PIV-1_00004.npy
PIV-1_00005.npy
PIV-1_00006.npy
PIV-1_00007.npy
PIV-1_00008.npy
PIV-1_00009.npy
PIV-1_00010.npy
PIV-1_00011.npy
PIV-1_00012.npy
PIV-1_00013.npy
PIV-1_00014.npy
PIV-1_00015.npy
PIV-1_00016.npy
PIV-1_00017.npy
PIV-1_00018.npy
PIV-1_00019.npy
PIV-1_00020.npy
PIV-1_00021.npy
PIV-1_00022.npy
PIV-1_00023.npy
PIV-1_00024.npy
PIV-1_00025.npy
PIV-1_00026.npy
PIV-1_00027.npy
PIV-1_00028.npy
PIV-1_00029.npy
PIV-1_00030.npy
PIV-1_00031.npy
PIV-1_00032.npy
PIV-1_00033.npy
PIV-1_00034.npy
PIV-1_00035.npy
PIV-1_00036.npy
PIV-1_00037.npy
PIV-1_00038.npy
PIV-1_00039.npy
PIV-1_00040.npy
PIV-1_00041.npy
PIV-1_00042.npy
PIV-1_00043.npy
PIV-1_00044.npy
PIV-1_00045.npy
PIV-1_00046.npy
PIV-1_00047.npy
PIV-1_00048.npy
PIV-1_00049.npy
PIV-1_00050.npy
PIV-1_00051.npy
PIV-1_00052.npy
PIV-1_00053.npy
PIV-1_00054.npy
PIV-1_00055.npy
PIV-1_00056.npy
PIV-1_00057.npy
PIV-1_00058.npy
PIV-1_00059.npy
PIV-1_00060.npy
PIV-1_00061.npy
PIV-1_00062.npy
PIV-1_00

In [19]:
print(re.findall(r'\d+', 'PIV-1_00176.npy'))
print(re.findall(r'\d+', 'PIV-1_00176.npy')[1])
print(type(re.findall(r'\d+', 'PIV-1_00176.npy')[1]))
print(int(re.findall(r'\d+', 'PIV-1_00176.npy')[1]))
print(int('005'))
# print(sorted([int(005), int(002), int(001), int(009), int(006)]))

['1', '00176']
00176
<class 'str'>
176
5


In [11]:
import os
import re
from collections import defaultdict

flow_files = os.listdir(f"D:\\Code\\PIV_dataset\\dataset")

# 使用字典存储每个分组的文件名列表
groups = defaultdict(list)

# 将文件名按照"PIV-"后面的数字进行分组
for file in flow_files:
    group_num = re.findall(r'\d+', file)[0]
    groups[group_num].append(file)
    
# 对每个分组的文件名列表进行排序，并将排序后的列表合并成一个有序列表
sorted_flow_files = []
for group_num in sorted(groups.keys(), key=int):
    sorted_group_files = sorted(groups[group_num], key=lambda x: int(re.findall(r'\d+', x)[1]))
    sorted_flow_files += sorted_group_files

# print(sorted_flow_files)
for file in sorted_flow_files:
    print(file)


PIV-1_00001.npy
PIV-1_00002.npy
PIV-1_00003.npy
PIV-1_00004.npy
PIV-1_00005.npy
PIV-1_00006.npy
PIV-1_00007.npy
PIV-1_00008.npy
PIV-1_00009.npy
PIV-1_00010.npy
PIV-1_00011.npy
PIV-1_00012.npy
PIV-1_00013.npy
PIV-1_00014.npy
PIV-1_00015.npy
PIV-1_00016.npy
PIV-1_00017.npy
PIV-1_00018.npy
PIV-1_00019.npy
PIV-1_00020.npy
PIV-1_00021.npy
PIV-1_00022.npy
PIV-1_00023.npy
PIV-1_00024.npy
PIV-1_00025.npy
PIV-1_00026.npy
PIV-1_00027.npy
PIV-1_00028.npy
PIV-1_00029.npy
PIV-1_00030.npy
PIV-1_00031.npy
PIV-1_00032.npy
PIV-1_00033.npy
PIV-1_00034.npy
PIV-1_00035.npy
PIV-1_00036.npy
PIV-1_00037.npy
PIV-1_00038.npy
PIV-1_00039.npy
PIV-1_00040.npy
PIV-1_00041.npy
PIV-1_00042.npy
PIV-1_00043.npy
PIV-1_00044.npy
PIV-1_00045.npy
PIV-1_00046.npy
PIV-1_00047.npy
PIV-1_00048.npy
PIV-1_00049.npy
PIV-1_00050.npy
PIV-1_00051.npy
PIV-1_00052.npy
PIV-1_00053.npy
PIV-1_00054.npy
PIV-1_00055.npy
PIV-1_00056.npy
PIV-1_00057.npy
PIV-1_00058.npy
PIV-1_00059.npy
PIV-1_00060.npy
PIV-1_00061.npy
PIV-1_00062.npy
PIV-1_00

In [8]:
from natsort import natsorted
import os

flow_files = os.listdir(f"D:\\Code\\PIV_dataset\\dataset")
file_names = natsorted(flow_files, reverse=False,)
print(file_names)

['PIV-1_00000.npy', 'PIV-1_00001.npy', 'PIV-1_00002.npy', 'PIV-1_00003.npy', 'PIV-1_00004.npy', 'PIV-1_00005.npy', 'PIV-1_00006.npy', 'PIV-1_00007.npy', 'PIV-1_00008.npy', 'PIV-1_00009.npy', 'PIV-1_00010.npy', 'PIV-1_00011.npy', 'PIV-1_00012.npy', 'PIV-1_00013.npy', 'PIV-1_00014.npy', 'PIV-1_00015.npy', 'PIV-1_00016.npy', 'PIV-1_00017.npy', 'PIV-1_00018.npy', 'PIV-1_00019.npy', 'PIV-1_00020.npy', 'PIV-1_00021.npy', 'PIV-1_00022.npy', 'PIV-1_00023.npy', 'PIV-1_00024.npy', 'PIV-1_00025.npy', 'PIV-1_00026.npy', 'PIV-1_00027.npy', 'PIV-1_00028.npy', 'PIV-1_00029.npy', 'PIV-1_00030.npy', 'PIV-1_00031.npy', 'PIV-1_00032.npy', 'PIV-1_00033.npy', 'PIV-1_00034.npy', 'PIV-1_00035.npy', 'PIV-1_00036.npy', 'PIV-1_00037.npy', 'PIV-1_00038.npy', 'PIV-1_00039.npy', 'PIV-1_00040.npy', 'PIV-1_00041.npy', 'PIV-1_00042.npy', 'PIV-1_00043.npy', 'PIV-1_00044.npy', 'PIV-1_00045.npy', 'PIV-1_00046.npy', 'PIV-1_00047.npy', 'PIV-1_00048.npy', 'PIV-1_00049.npy', 'PIV-1_00050.npy', 'PIV-1_00051.npy', 'PIV-1_0005

In [2]:
# 验证列表减法
a = ['ab', 'aa', 'ac', 'ad', 'ae', 'bb']
b = ['aa', 'ad', 'ae']
c = list(set(a) - set(b))
print(c)
c = [file for file in a if file not in b]
print(c)

['bb', 'ac', 'ab']
['ab', 'ac', 'bb']


In [5]:
# 验证最值的计算
import numpy as np

# arr.shape = (3, 5, 5)
arr = np.random.randint(1, 10, size=(3, 5, 5)).astype(np.float32)
print(arr)

# np.savetxt("..\\data\\minimax\\flow_max_final.txt", flow_max_final, fmt="%.12f")
# np.savetxt("..\\data\\minimax\\flow_min_final.txt", flow_min_final, fmt="%.12f")

# Load the maximum and minimum values saved locally.
flow_max_final = np.loadtxt("data\\minimax\\flow_max_final.txt")
flow_min_final = np.loadtxt("data\\minimax\\flow_min_final.txt")

# flow_max_final = np.array([1, 2, 3])
# flow_min_final = np.array([10, 20, 30])
flow_max_final = flow_max_final[:, np.newaxis, np.newaxis]
flow_min_final = flow_min_final[:, np.newaxis, np.newaxis]
print(flow_max_final)
# Normalized arr array
# arr = (arr - flow_min_final) / (flow_max_final - flow_min_final)
arr = arr * flow_max_final
print(arr)



[[[4. 1. 2. 3. 4.]
  [2. 3. 2. 7. 6.]
  [7. 3. 2. 4. 8.]
  [2. 7. 1. 3. 4.]
  [7. 5. 1. 9. 8.]]

 [[5. 6. 1. 2. 4.]
  [8. 1. 5. 4. 5.]
  [4. 5. 6. 5. 1.]
  [7. 8. 8. 4. 1.]
  [6. 6. 2. 4. 1.]]

 [[3. 8. 2. 1. 8.]
  [2. 7. 9. 5. 7.]
  [8. 9. 4. 3. 4.]
  [6. 8. 4. 7. 6.]
  [6. 2. 6. 8. 3.]]]
[[[  1.26599657]]

 [[  2.85837173]]

 [[179.997345  ]]]
[[[   5.0639863     1.26599657    2.53199315    3.79798972    5.0639863 ]
  [   2.53199315    3.79798972    2.53199315    8.86197603    7.59597945]
  [   8.86197603    3.79798972    2.53199315    5.0639863    10.1279726 ]
  [   2.53199315    8.86197603    1.26599657    3.79798972    5.0639863 ]
  [   8.86197603    6.32998287    1.26599657   11.39396917   10.1279726 ]]

 [[  14.29185868   17.15023041    2.85837173    5.71674347   11.43348694]
  [  22.86697388    2.85837173   14.29185868   11.43348694   14.29185868]
  [  11.43348694   14.29185868   17.15023041   14.29185868    2.85837173]
  [  20.00860215   22.86697388   22.86697388   11.43348694

In [7]:
# 验证最值的计算
import numpy as np

arr = np.random.randint(1, 10, size=(3, 6, 6)).astype(np.float32)
print(arr)

flow_max_final = np.array([100, 200, 300])
flow_min_final = np.array([1, 2, 3])

flow_max_final = flow_max_final[:, np.newaxis, np.newaxis]
flow_min_final = flow_min_final[:, np.newaxis, np.newaxis]
print(flow_max_final.shape)
print(flow_max_final[0:2, :, :])

# Normalized arr array
arr2C = (arr[0:2, :, :] - flow_min_final[0:2, :, :]) / (flow_max_final[0:2, :, :] - flow_min_final[0:2, :, :])

print(arr2C)



[[[1. 4. 4. 7. 3. 7.]
  [8. 4. 8. 6. 9. 9.]
  [5. 2. 4. 2. 1. 4.]
  [2. 1. 3. 4. 8. 3.]
  [5. 8. 4. 7. 1. 3.]
  [7. 6. 6. 2. 8. 5.]]

 [[1. 3. 9. 5. 4. 8.]
  [2. 8. 5. 7. 7. 1.]
  [9. 3. 1. 5. 8. 5.]
  [2. 2. 7. 8. 2. 6.]
  [6. 9. 6. 1. 1. 1.]
  [8. 6. 6. 1. 3. 8.]]

 [[9. 5. 5. 9. 8. 7.]
  [4. 1. 9. 3. 3. 3.]
  [6. 1. 1. 8. 8. 1.]
  [3. 9. 8. 6. 5. 4.]
  [6. 8. 9. 6. 7. 9.]
  [7. 7. 5. 2. 7. 6.]]]
(3, 1, 1)
[[[100]]

 [[200]]]
[[[ 0.          0.03030303  0.03030303  0.06060606  0.02020202
    0.06060606]
  [ 0.07070707  0.03030303  0.07070707  0.05050505  0.08080808
    0.08080808]
  [ 0.04040404  0.01010101  0.03030303  0.01010101  0.
    0.03030303]
  [ 0.01010101  0.          0.02020202  0.03030303  0.07070707
    0.02020202]
  [ 0.04040404  0.07070707  0.03030303  0.06060606  0.
    0.02020202]
  [ 0.06060606  0.05050505  0.05050505  0.01010101  0.07070707
    0.04040404]]

 [[-0.00505051  0.00505051  0.03535354  0.01515152  0.01010101
    0.03030303]
  [ 0.          0.03030303  0

In [2]:
# 验证二维矩阵数据的pooling下采样方式
# As pooling is often used in CNN, the input array is usually 3D. So I made a function that works on either 2D or 3D arrays.
import numpy as np
def pooling(mat,ksize,method='max',pad=False):
    """
    Non-overlapping pooling on 2D or 3D data.

    <mat>: ndarray, input array to pool.
    <ksize>: tuple of 2, kernel size in (ky, kx).
    <method>: str, 'max for max-pooling, 
                   'mean' for mean-pooling.
    <pad>: bool, pad <mat> or not. If no pad, output has size
           n//f, n being <mat> size, f being kernel size.
           if pad, output has size ceil(n/f).

    Return <result>: pooled matrix.
    """

    m, n = mat.shape[:2]
    ky,kx=ksize

    _ceil=lambda x,y: int(np.ceil(x/float(y)))

    if pad:
        ny=_ceil(m,ky)
        nx=_ceil(n,kx)
        size=(ny*ky, nx*kx)+mat.shape[2:]
        mat_pad=np.full(size,np.nan)
        mat_pad[:m,:n,...]=mat
    else:
        ny=m//ky
        nx=n//kx
        mat_pad=mat[:ny*ky, :nx*kx, ...]

    new_shape=(ny,ky,nx,kx)+mat.shape[2:]

    if method=='max':
        result=np.nanmax(mat_pad.reshape(new_shape),axis=(1,3))
    else:
        result=np.nanmean(mat_pad.reshape(new_shape),axis=(1,3))

    return result

# 随机生成一个二维numpy数组[16，16]
np.random.seed(928)
Random_array = np.random.randint(1,10,size=(8,8)).astype(np.float32)
print(Random_array)
# 对数组进行pooling下采样
result = pooling(Random_array, (4, 4), method='mean', pad=False)
print(result)


[[9. 4. 6. 4. 8. 7. 9. 8.]
 [2. 9. 2. 8. 2. 8. 1. 7.]
 [9. 4. 3. 4. 8. 3. 9. 6.]
 [4. 8. 3. 7. 4. 1. 6. 4.]
 [5. 8. 5. 9. 9. 2. 9. 1.]
 [2. 2. 2. 1. 8. 3. 9. 5.]
 [2. 1. 8. 1. 7. 3. 5. 3.]
 [8. 7. 9. 1. 9. 4. 2. 4.]]
[[5.375  5.6875]
 [4.4375 5.1875]]


In [3]:
# Sometimes you may want to perform overlapping pooling, at a stride not equal to the kernel size. Here is a function that does that, with or without padding:
import numpy as np
def asStride(arr,sub_shape,stride):
    """
    Get a strided sub-matrices view of an ndarray.
    See also skimage.util.shape.view_as_windows()
    """
    s0,s1=arr.strides[:2]
    m1,n1=arr.shape[:2]
    m2,n2=sub_shape
    view_shape=(1+(m1-m2)//stride[0],1+(n1-n2)//stride[1],m2,n2)+arr.shape[2:]
    strides=(stride[0]*s0,stride[1]*s1,s0,s1)+arr.strides[2:]
    subs=np.lib.stride_tricks.as_strided(arr,view_shape,strides=strides)
    return subs

def poolingOverlap(mat,ksize,stride=None,method='max',pad=False):
    """
    Overlapping pooling on 2D or 3D data.

    <mat>: ndarray, input array to pool.
    <ksize>: tuple of 2, kernel size in (ky, kx).
    <stride>: tuple of 2 or None, stride of pooling window.
              If None, same as <ksize> (non-overlapping pooling).
    <method>: str, 'max for max-pooling,
                   'mean' for mean-pooling.
    <pad>: bool, pad <mat> or not. If no pad, output has size
           (n-f)//s+1, n being <mat> size, f being kernel size, s stride.
           if pad, output has size ceil(n/s).

    Return <result>: pooled matrix.
    """

    m, n = mat.shape[:2]
    ky,kx=ksize
    if stride is None:
        stride=(ky,kx)
    sy,sx=stride

    _ceil=lambda x,y: int(np.ceil(x/float(y)))

    if pad:
        ny=_ceil(m,sy)
        nx=_ceil(n,sx)
        size=((ny-1)*sy+ky, (nx-1)*sx+kx) + mat.shape[2:]
        mat_pad=np.full(size,np.nan)
        mat_pad[:m,:n,...]=mat
    else:
        mat_pad=mat[:(m-ky)//sy*sy+ky, :(n-kx)//sx*sx+kx, ...]

    view=asStride(mat_pad,ksize,stride)

    if method=='max':
        result=np.nanmax(view,axis=(2,3))
    else:
        result=np.nanmean(view,axis=(2,3))

    return result

# 随机生成一个二维numpy数组[16，16]
np.random.seed(928)
Random_array = np.random.randint(1,10,size=(8,8)).astype(np.float32)
print(Random_array)
# 对数组进行pooling下采样
result = pooling(mat=Random_array, ksize=(4, 4), method='mean', pad=False)
print(result)


[[9. 4. 6. 4. 8. 7. 9. 8.]
 [2. 9. 2. 8. 2. 8. 1. 7.]
 [9. 4. 3. 4. 8. 3. 9. 6.]
 [4. 8. 3. 7. 4. 1. 6. 4.]
 [5. 8. 5. 9. 9. 2. 9. 1.]
 [2. 2. 2. 1. 8. 3. 9. 5.]
 [2. 1. 8. 1. 7. 3. 5. 3.]
 [8. 7. 9. 1. 9. 4. 2. 4.]]
[[5.375  5.6875]
 [4.4375 5.1875]]


In [7]:
import numpy as np

def poolingOverlap3D(arr3d, ksize, stride=None, method='max', pad=False):
    """
    Perform overlapping pooling on a 3D numpy array.

    Args:
        arr3d (numpy.ndarray): 3D input array with shape (3, m, n).
        ksize (tuple): Kernel size in (ky, kx).
        stride (tuple, optional): Stride of pooling window. If None, same as ksize (non-overlapping pooling).
        method (str, optional): Pooling method, 'max' for max-pooling, 'mean' for mean-pooling.
        pad (bool, optional): Whether to pad the input array or not.

    Returns:
        numpy.ndarray: 3D output array with shape (3, m', n'), where m' and n' depend on the pooling parameters.
    """
    pooled_2d = []
    for i in range(arr3d.shape[0]):
        pooled_2d.append(poolingOverlap(arr3d[i, :, :], ksize, stride, method, pad))

    return np.stack(pooled_2d, axis=0)

# Example usage
arr3d = np.random.rand(3, 4, 4)
print(arr3d)
pooled_arr3d = poolingOverlap3D(arr3d, ksize=(4, 4), stride=(4, 4), method='max', pad=False)
print(pooled_arr3d.shape)
print(pooled_arr3d)

[[[0.18542916 0.01280627 0.76975297 0.095359  ]
  [0.11765776 0.43507597 0.9468655  0.88683195]
  [0.07732088 0.96016226 0.9591509  0.64032911]
  [0.31097954 0.13868875 0.40029898 0.70392099]]

 [[0.02091221 0.09255401 0.85940721 0.89329041]
  [0.43114045 0.91237775 0.05280471 0.44199884]
  [0.24991783 0.47491592 0.02366293 0.90400747]
  [0.48115119 0.15411873 0.62798511 0.15834168]]

 [[0.98078656 0.15985038 0.31990958 0.05466391]
  [0.95865931 0.36998048 0.77360596 0.23468272]
  [0.23046598 0.96774104 0.75541875 0.78105094]
  [0.90380636 0.28565162 0.85800153 0.94285162]]]
(3, 1, 1)
[[[0.96016226]]

 [[0.91237775]]

 [[0.98078656]]]


In [17]:
# 验证源代码中的bicubic方法
import math
import numpy as np
import torch


def cubic(x):
    """cubic function used for calculate_weights_indices."""
    absx = torch.abs(x)
    absx2 = absx**2
    absx3 = absx**3
    return (1.5 * absx3 - 2.5 * absx2 + 1) * (
        (absx <= 1).type_as(absx)) + (-0.5 * absx3 + 2.5 * absx2 - 4 * absx + 2) * (((absx > 1) *
                                                                                     (absx <= 2)).type_as(absx))


def calculate_weights_indices(in_length, out_length, scale, kernel, kernel_width, antialiasing):
    """Calculate weights and indices, used for imresize function.

    Args:
        in_length (int): Input length.
        out_length (int): Output length.
        scale (float): Scale factor.
        kernel_width (int): Kernel width.
        antialisaing (bool): Whether to apply anti-aliasing when downsampling.
    """

    if (scale < 1) and antialiasing:
        # Use a modified kernel (larger kernel width) to simultaneously
        # interpolate and antialias
        kernel_width = kernel_width / scale

    # Output-space coordinates
    x = torch.linspace(1, out_length, out_length)

    # Input-space coordinates. Calculate the inverse mapping such that 0.5
    # in output space maps to 0.5 in input space, and 0.5 + scale in output
    # space maps to 1.5 in input space.
    u = x / scale + 0.5 * (1 - 1 / scale)

    # What is the left-most pixel that can be involved in the computation?
    left = torch.floor(u - kernel_width / 2)

    # What is the maximum number of pixels that can be involved in the
    # computation?  Note: it's OK to use an extra pixel here; if the
    # corresponding weights are all zero, it will be eliminated at the end
    # of this function.
    p = math.ceil(kernel_width) + 2

    # The indices of the input pixels involved in computing the k-th output
    # pixel are in row k of the indices matrix.
    indices = left.view(out_length, 1).expand(out_length, p) + torch.linspace(0, p - 1, p).view(1, p).expand(
        out_length, p)

    # The weights used to compute the k-th output pixel are in row k of the
    # weights matrix.
    distance_to_center = u.view(out_length, 1).expand(out_length, p) - indices

    # apply cubic kernel
    if (scale < 1) and antialiasing:
        weights = scale * cubic(distance_to_center * scale)
    else:
        weights = cubic(distance_to_center)

    # Normalize the weights matrix so that each row sums to 1.
    weights_sum = torch.sum(weights, 1).view(out_length, 1)
    weights = weights / weights_sum.expand(out_length, p)

    # If a column in weights is all zero, get rid of it. only consider the
    # first and last column.
    weights_zero_tmp = torch.sum((weights == 0), 0)
    if not math.isclose(weights_zero_tmp[0], 0, rel_tol=1e-6):
        indices = indices.narrow(1, 1, p - 2)
        weights = weights.narrow(1, 1, p - 2)
    if not math.isclose(weights_zero_tmp[-1], 0, rel_tol=1e-6):
        indices = indices.narrow(1, 0, p - 2)
        weights = weights.narrow(1, 0, p - 2)
    weights = weights.contiguous()
    indices = indices.contiguous()
    sym_len_s = -indices.min() + 1
    sym_len_e = indices.max() - in_length
    indices = indices + sym_len_s - 1
    return weights, indices, int(sym_len_s), int(sym_len_e)


@torch.no_grad()
def imresize(img, scale, antialiasing=True):
    """imresize function same as MATLAB.

    It now only supports bicubic.
    The same scale applies for both height and width.

    Args:
        img (Tensor | Numpy array):
            Tensor: Input image with shape (c, h, w), [0, 1] range.
            Numpy: Input image with shape (h, w, c), [0, 1] range.
        scale (float): Scale factor. The same scale applies for both height
            and width.
        antialisaing (bool): Whether to apply anti-aliasing when downsampling.
            Default: True.

    Returns:
        Tensor: Output image with shape (c, h, w), [0, 1] range, w/o round.
    """
    squeeze_flag = False
    if type(img).__module__ == np.__name__:  # numpy type
        numpy_type = True
        if img.ndim == 2:
            img = img[:, :, None]
            squeeze_flag = True
        img = torch.from_numpy(img.transpose(2, 0, 1)).float()
    else:
        numpy_type = False
        if img.ndim == 2:
            img = img.unsqueeze(0)
            squeeze_flag = True

    in_c, in_h, in_w = img.size()
    out_h, out_w = math.ceil(in_h * scale), math.ceil(in_w * scale)
    kernel_width = 4
    kernel = 'cubic'

    # get weights and indices
    weights_h, indices_h, sym_len_hs, sym_len_he = calculate_weights_indices(in_h, out_h, scale, kernel, kernel_width,
                                                                             antialiasing)
    weights_w, indices_w, sym_len_ws, sym_len_we = calculate_weights_indices(in_w, out_w, scale, kernel, kernel_width,
                                                                             antialiasing)
    # process H dimension
    # symmetric copying
    img_aug = torch.FloatTensor(in_c, in_h + sym_len_hs + sym_len_he, in_w)
    img_aug.narrow(1, sym_len_hs, in_h).copy_(img)

    sym_patch = img[:, :sym_len_hs, :]
    inv_idx = torch.arange(sym_patch.size(1) - 1, -1, -1).long()
    sym_patch_inv = sym_patch.index_select(1, inv_idx)
    img_aug.narrow(1, 0, sym_len_hs).copy_(sym_patch_inv)

    sym_patch = img[:, -sym_len_he:, :]
    inv_idx = torch.arange(sym_patch.size(1) - 1, -1, -1).long()
    sym_patch_inv = sym_patch.index_select(1, inv_idx)
    img_aug.narrow(1, sym_len_hs + in_h, sym_len_he).copy_(sym_patch_inv)

    out_1 = torch.FloatTensor(in_c, out_h, in_w)
    kernel_width = weights_h.size(1)
    for i in range(out_h):
        idx = int(indices_h[i][0])
        for j in range(in_c):
            out_1[j, i, :] = img_aug[j, idx:idx + kernel_width, :].transpose(0, 1).mv(weights_h[i])

    # process W dimension
    # symmetric copying
    out_1_aug = torch.FloatTensor(in_c, out_h, in_w + sym_len_ws + sym_len_we)
    out_1_aug.narrow(2, sym_len_ws, in_w).copy_(out_1)

    sym_patch = out_1[:, :, :sym_len_ws]
    inv_idx = torch.arange(sym_patch.size(2) - 1, -1, -1).long()
    sym_patch_inv = sym_patch.index_select(2, inv_idx)
    out_1_aug.narrow(2, 0, sym_len_ws).copy_(sym_patch_inv)

    sym_patch = out_1[:, :, -sym_len_we:]
    inv_idx = torch.arange(sym_patch.size(2) - 1, -1, -1).long()
    sym_patch_inv = sym_patch.index_select(2, inv_idx)
    out_1_aug.narrow(2, sym_len_ws + in_w, sym_len_we).copy_(sym_patch_inv)

    out_2 = torch.FloatTensor(in_c, out_h, out_w)
    kernel_width = weights_w.size(1)
    for i in range(out_w):
        idx = int(indices_w[i][0])
        for j in range(in_c):
            out_2[j, :, i] = out_1_aug[j, :, idx:idx + kernel_width].mv(weights_w[i])

    if squeeze_flag:
        out_2 = out_2.squeeze(0)
    if numpy_type:
        out_2 = out_2.numpy()
        if not squeeze_flag:
            out_2 = out_2.transpose(1, 2, 0)

    return out_2

# 随机生成一个二维numpy数组[16，16]
np.random.seed(928)
Random_array = np.random.randint(1,10,size=(12,12)).astype(np.float32)
print(Random_array)
# 对数组进行bicubic下采样
result = imresize(img=Random_array, scale=0.25, antialiasing=True)
print(result)



[[9. 4. 6. 4. 8. 7. 9. 8. 2. 9. 2. 8.]
 [2. 8. 1. 7. 9. 4. 3. 4. 8. 3. 9. 6.]
 [4. 8. 3. 7. 4. 1. 6. 4. 5. 8. 5. 9.]
 [9. 2. 9. 1. 2. 2. 2. 1. 8. 3. 9. 5.]
 [2. 1. 8. 1. 7. 3. 5. 3. 8. 7. 9. 1.]
 [9. 4. 2. 4. 2. 8. 9. 6. 6. 5. 4. 1.]
 [4. 7. 4. 5. 1. 2. 9. 4. 9. 2. 9. 4.]
 [7. 5. 7. 5. 9. 6. 9. 7. 2. 1. 5. 1.]
 [1. 3. 3. 8. 6. 7. 5. 9. 2. 3. 7. 3.]
 [2. 1. 9. 1. 1. 8. 9. 1. 7. 7. 4. 8.]
 [3. 6. 9. 2. 4. 8. 1. 4. 2. 7. 9. 6.]
 [8. 4. 6. 9. 5. 7. 6. 2. 5. 8. 7. 4.]]
[[5.1915207 4.8777647 6.1370745]
 [4.5231524 5.3117466 4.6726084]
 [4.932727  5.361453  5.429453 ]]


In [18]:
import numpy as np

def imresize3D(img, scale, antialiasing=True):
    """
        Perform overlapping imresize on a 3D numpy array.
        
        Args:
            img (numpy.ndarray): 3D input array with shape (3, m, n).
            scale (float): Scale factor.
            antialisaing (bool): Whether to apply anti-aliasing when downsampling.
            
        Returns:
            numpy.ndarray: 3D output array with shape (3, m', n'), where m' and n' depend on the pooling parameters.
    """
    out_2d = []
    for i in range(img.shape[0]):
        out_2d.append(imresize(img[i, :, :], scale, antialiasing))

    return np.stack(out_2d, axis=0)
    
np.random.seed(928)
arr3d_ = np.random.randint(1,10,size=(3, 12, 12)).astype(np.float32)
print(arr3d_)
resizeed_arr3d = imresize3D(img=arr3d_, scale=0.25, antialiasing=True)
print(resizeed_arr3d.shape)
print(resizeed_arr3d)

[[[9. 4. 6. 4. 8. 7. 9. 8. 2. 9. 2. 8.]
  [2. 8. 1. 7. 9. 4. 3. 4. 8. 3. 9. 6.]
  [4. 8. 3. 7. 4. 1. 6. 4. 5. 8. 5. 9.]
  [9. 2. 9. 1. 2. 2. 2. 1. 8. 3. 9. 5.]
  [2. 1. 8. 1. 7. 3. 5. 3. 8. 7. 9. 1.]
  [9. 4. 2. 4. 2. 8. 9. 6. 6. 5. 4. 1.]
  [4. 7. 4. 5. 1. 2. 9. 4. 9. 2. 9. 4.]
  [7. 5. 7. 5. 9. 6. 9. 7. 2. 1. 5. 1.]
  [1. 3. 3. 8. 6. 7. 5. 9. 2. 3. 7. 3.]
  [2. 1. 9. 1. 1. 8. 9. 1. 7. 7. 4. 8.]
  [3. 6. 9. 2. 4. 8. 1. 4. 2. 7. 9. 6.]
  [8. 4. 6. 9. 5. 7. 6. 2. 5. 8. 7. 4.]]

 [[4. 6. 4. 4. 7. 8. 3. 4. 3. 7. 1. 8.]
  [7. 9. 2. 7. 7. 4. 7. 3. 6. 5. 9. 6.]
  [3. 2. 2. 9. 7. 4. 3. 7. 3. 9. 7. 7.]
  [9. 8. 1. 5. 5. 1. 8. 3. 3. 1. 9. 8.]
  [8. 7. 9. 4. 8. 4. 8. 7. 2. 5. 4. 3.]
  [2. 6. 8. 2. 5. 7. 5. 4. 5. 8. 7. 6.]
  [3. 1. 2. 8. 9. 3. 4. 8. 8. 9. 6. 5.]
  [8. 4. 6. 7. 2. 7. 7. 1. 1. 9. 8. 5.]
  [9. 2. 9. 6. 8. 5. 9. 3. 6. 6. 5. 8.]
  [9. 9. 7. 1. 8. 1. 7. 9. 7. 4. 5. 7.]
  [4. 1. 1. 2. 8. 6. 2. 4. 2. 7. 1. 7.]
  [7. 3. 4. 4. 9. 2. 4. 3. 8. 8. 3. 1.]]

 [[8. 1. 1. 5. 9. 9. 8. 8. 2. 6. 1. 

In [2]:
# 验证对标matlab的bicubic-python的方法
# if kernel == 'cubic':
#     weight = cubic_contribution(buffer_pos)
# elif kernel == 'gaussian':
#     weight = gaussian_contribution(buffer_pos, sigma=sigma)
# 只支持两种核函数，分别是cubic和gaussian
import numpy as np
import torch
from torch import cuda
import core

# We support 2, 3, and 4-dim Tensors
# (H x W, C x H x W, and B x C x H x W, respectively).
# Larger batch sizes are also supported.
# x = torch.randn(1, 3, 456, 321)
np.random.seed(928)
Random_array = np.random.randint(1,10,size=(1, 1, 20, 20)).astype(np.float32)
x = torch.from_numpy(Random_array)
print(x)

# If the input is on a CUDA device, all computations will be done using the GPU.
if cuda.is_available():
    x = x.cuda()

# Resize by scale
x_resized_1 = core.imresize(x, scale=0.25)

# Resize by resolution (456, 321) -> (123, 456)
x_resized_2 = core.imresize(x, sizes=(2, 2))

# Resize without antialiasing (Not compatible with MATLAB)
x_resized_3 = core.imresize(x, scale=0.25, antialiasing=True)

# Resize without antialiasing (Compatible with MATLAB)
x_resized_4 = core.imresize(x, scale=0.25, antialiasing=True, kernel='gaussian', sigma=1)

print(x_resized_1)
print(x_resized_2)
print(x_resized_3)
print(x_resized_4)


tensor([[[[9., 4., 6., 4., 8., 7., 9., 8., 2., 9., 2., 8., 2., 8., 1., 7., 9.,
           4., 3., 4.],
          [8., 3., 9., 6., 4., 8., 3., 7., 4., 1., 6., 4., 5., 8., 5., 9., 9.,
           2., 9., 1.],
          [2., 2., 2., 1., 8., 3., 9., 5., 2., 1., 8., 1., 7., 3., 5., 3., 8.,
           7., 9., 1.],
          [9., 4., 2., 4., 2., 8., 9., 6., 6., 5., 4., 1., 4., 7., 4., 5., 1.,
           2., 9., 4.],
          [9., 2., 9., 4., 7., 5., 7., 5., 9., 6., 9., 7., 2., 1., 5., 1., 1.,
           3., 3., 8.],
          [6., 7., 5., 9., 2., 3., 7., 3., 2., 1., 9., 1., 1., 8., 9., 1., 7.,
           7., 4., 8.],
          [3., 6., 9., 2., 4., 8., 1., 4., 2., 7., 9., 6., 8., 4., 6., 9., 5.,
           7., 6., 2.],
          [5., 8., 7., 4., 4., 6., 4., 4., 7., 8., 3., 4., 3., 7., 1., 8., 7.,
           9., 2., 7.],
          [7., 4., 7., 3., 6., 5., 9., 6., 3., 2., 2., 9., 7., 4., 3., 7., 3.,
           9., 7., 7.],
          [9., 8., 1., 5., 5., 1., 8., 3., 3., 1., 9., 8., 8., 7., 9., 4.

In [13]:
import numpy as np
import torch
from torch import cuda
import core

# We support 2, 3, and 4-dim Tensors
# (H x W, C x H x W, and B x C x H x W, respectively).
# Larger batch sizes are also supported.
# x = torch.randn(1, 3, 456, 321)
np.random.seed(928)
Random_array = np.random.randint(1,10,size=(1, 3, 12, 12)).astype(np.float32)
x = torch.from_numpy(Random_array)
print(x)

# If the input is on a CUDA device, all computations will be done using the GPU.
if cuda.is_available():
    x = x.cuda()

# Resize without antialiasing (Compatible with MATLAB)
x_resized_3d = core.imresize(x, scale=0.25, antialiasing=True, kernel='gaussian', sigma=0.5)

print(x_resized_3d)

x_resized_2d = core.imresize(x[:, 0:1, :, :], scale=0.25, antialiasing=True, kernel='gaussian', sigma=0.5)
print(x_resized_2d)


tensor([[[[9., 4., 6., 4., 8., 7., 9., 8., 2., 9., 2., 8.],
          [2., 8., 1., 7., 9., 4., 3., 4., 8., 3., 9., 6.],
          [4., 8., 3., 7., 4., 1., 6., 4., 5., 8., 5., 9.],
          [9., 2., 9., 1., 2., 2., 2., 1., 8., 3., 9., 5.],
          [2., 1., 8., 1., 7., 3., 5., 3., 8., 7., 9., 1.],
          [9., 4., 2., 4., 2., 8., 9., 6., 6., 5., 4., 1.],
          [4., 7., 4., 5., 1., 2., 9., 4., 9., 2., 9., 4.],
          [7., 5., 7., 5., 9., 6., 9., 7., 2., 1., 5., 1.],
          [1., 3., 3., 8., 6., 7., 5., 9., 2., 3., 7., 3.],
          [2., 1., 9., 1., 1., 8., 9., 1., 7., 7., 4., 8.],
          [3., 6., 9., 2., 4., 8., 1., 4., 2., 7., 9., 6.],
          [8., 4., 6., 9., 5., 7., 6., 2., 5., 8., 7., 4.]],

         [[4., 6., 4., 4., 7., 8., 3., 4., 3., 7., 1., 8.],
          [7., 9., 2., 7., 7., 4., 7., 3., 6., 5., 9., 6.],
          [3., 2., 2., 9., 7., 4., 3., 7., 3., 9., 7., 7.],
          [9., 8., 1., 5., 5., 1., 8., 3., 3., 1., 9., 8.],
          [8., 7., 9., 4., 8., 4., 8.,

In [ ]:
# 验证imresize函数对于二维数组的处理
import math
import numpy as np
import torch


def cubic(x):
    """cubic function used for calculate_weights_indices."""
    absx = torch.abs(x)
    absx2 = absx ** 2
    absx3 = absx ** 3
    return (1.5 * absx3 - 2.5 * absx2 + 1) * (
        (absx <= 1).type_as(absx)) + (-0.5 * absx3 + 2.5 * absx2 - 4 * absx + 2) * (((absx > 1) *
                                                                                     (absx <= 2)).type_as(absx))


def calculate_weights_indices(in_length, out_length, scale, kernel, kernel_width, antialiasing):
    """Calculate weights and indices, used for imresize function.

    Args:
        in_length (int): Input length.
        out_length (int): Output length.
        scale (float): Scale factor.
        kernel_width (int): Kernel width.
        antialisaing (bool): Whether to apply anti-aliasing when downsampling.
    """

    if (scale < 1) and antialiasing:
        # Use a modified kernel (larger kernel width) to simultaneously
        # interpolate and antialias
        kernel_width = kernel_width / scale

    # Output-space coordinates
    x = torch.linspace(1, out_length, out_length)

    # Input-space coordinates. Calculate the inverse mapping such that 0.5
    # in output space maps to 0.5 in input space, and 0.5 + scale in output
    # space maps to 1.5 in input space.
    u = x / scale + 0.5 * (1 - 1 / scale)

    # What is the left-most pixel that can be involved in the computation?
    left = torch.floor(u - kernel_width / 2)

    # What is the maximum number of pixels that can be involved in the
    # computation?  Note: it's OK to use an extra pixel here; if the
    # corresponding weights are all zero, it will be eliminated at the end
    # of this function.
    p = math.ceil(kernel_width) + 2

    # The indices of the input pixels involved in computing the k-th output
    # pixel are in row k of the indices matrix.
    indices = left.view(out_length, 1).expand(out_length, p) + torch.linspace(0, p - 1, p).view(1, p).expand(
        out_length, p)

    # The weights used to compute the k-th output pixel are in row k of the
    # weights matrix.
    distance_to_center = u.view(out_length, 1).expand(out_length, p) - indices

    # apply cubic kernel
    if (scale < 1) and antialiasing:
        weights = scale * cubic(distance_to_center * scale)
    else:
        weights = cubic(distance_to_center)

    # Normalize the weights matrix so that each row sums to 1.
    weights_sum = torch.sum(weights, 1).view(out_length, 1)
    weights = weights / weights_sum.expand(out_length, p)

    # If a column in weights is all zero, get rid of it. only consider the
    # first and last column.
    weights_zero_tmp = torch.sum((weights == 0), 0)
    if not math.isclose(weights_zero_tmp[0], 0, rel_tol=1e-6):
        indices = indices.narrow(1, 1, p - 2)
        weights = weights.narrow(1, 1, p - 2)
    if not math.isclose(weights_zero_tmp[-1], 0, rel_tol=1e-6):
        indices = indices.narrow(1, 0, p - 2)
        weights = weights.narrow(1, 0, p - 2)
    weights = weights.contiguous()
    indices = indices.contiguous()
    sym_len_s = -indices.min() + 1
    sym_len_e = indices.max() - in_length
    indices = indices + sym_len_s - 1
    return weights, indices, int(sym_len_s), int(sym_len_e)


@torch.no_grad()
def imresize(img, scale, antialiasing=True):
    """imresize function same as MATLAB.

    It now only supports bicubic.
    The same scale applies for both height and width.

    Args:
        img (Tensor | Numpy array):
            Tensor: Input image with shape (c, h, w), [0, 1] range.
            Numpy: Input image with shape (h, w, c), [0, 1] range.
        scale (float): Scale factor. The same scale applies for both height
            and width.
        antialisaing (bool): Whether to apply anti-aliasing when downsampling.
            Default: True.

    Returns:
        Tensor: Output image with shape (c, h, w), [0, 1] range, w/o round.
    """
    squeeze_flag = False
    if type(img).__module__ == np.__name__:  # numpy type
        numpy_type = True
        if img.ndim == 2:
            img = img[:, :, None]
            squeeze_flag = True
        img = torch.from_numpy(img.transpose(2, 0, 1)).float()
        # img = torch.from_numpy(img).float()
    else:
        numpy_type = False
        if img.ndim == 2:
            img = img.unsqueeze(0)
            squeeze_flag = True

    in_c, in_h, in_w = img.size()
    out_h, out_w = math.ceil(in_h * scale), math.ceil(in_w * scale)
    kernel_width = 4
    kernel = 'cubic'

    # get weights and indices
    weights_h, indices_h, sym_len_hs, sym_len_he = calculate_weights_indices(in_h, out_h, scale, kernel, kernel_width,
                                                                             antialiasing)
    weights_w, indices_w, sym_len_ws, sym_len_we = calculate_weights_indices(in_w, out_w, scale, kernel, kernel_width,
                                                                             antialiasing)
    # process H dimension
    # symmetric copying
    img_aug = torch.FloatTensor(in_c, in_h + sym_len_hs + sym_len_he, in_w)
    img_aug.narrow(1, sym_len_hs, in_h).copy_(img)

    sym_patch = img[:, :sym_len_hs, :]
    inv_idx = torch.arange(sym_patch.size(1) - 1, -1, -1).long()
    sym_patch_inv = sym_patch.index_select(1, inv_idx)
    img_aug.narrow(1, 0, sym_len_hs).copy_(sym_patch_inv)

    sym_patch = img[:, -sym_len_he:, :]
    inv_idx = torch.arange(sym_patch.size(1) - 1, -1, -1).long()
    sym_patch_inv = sym_patch.index_select(1, inv_idx)
    img_aug.narrow(1, sym_len_hs + in_h, sym_len_he).copy_(sym_patch_inv)

    out_1 = torch.FloatTensor(in_c, out_h, in_w)
    kernel_width = weights_h.size(1)
    for i in range(out_h):
        idx = int(indices_h[i][0])
        for j in range(in_c):
            out_1[j, i, :] = img_aug[j, idx:idx + kernel_width, :].transpose(0, 1).mv(weights_h[i])

    # process W dimension
    # symmetric copying
    out_1_aug = torch.FloatTensor(in_c, out_h, in_w + sym_len_ws + sym_len_we)
    out_1_aug.narrow(2, sym_len_ws, in_w).copy_(out_1)

    sym_patch = out_1[:, :, :sym_len_ws]
    inv_idx = torch.arange(sym_patch.size(2) - 1, -1, -1).long()
    sym_patch_inv = sym_patch.index_select(2, inv_idx)
    out_1_aug.narrow(2, 0, sym_len_ws).copy_(sym_patch_inv)

    sym_patch = out_1[:, :, -sym_len_we:]
    inv_idx = torch.arange(sym_patch.size(2) - 1, -1, -1).long()
    sym_patch_inv = sym_patch.index_select(2, inv_idx)
    out_1_aug.narrow(2, sym_len_ws + in_w, sym_len_we).copy_(sym_patch_inv)

    out_2 = torch.FloatTensor(in_c, out_h, out_w)
    kernel_width = weights_w.size(1)
    for i in range(out_w):
        idx = int(indices_w[i][0])
        for j in range(in_c):
            out_2[j, :, i] = out_1_aug[j, :, idx:idx + kernel_width].mv(weights_w[i])

    if squeeze_flag:
        out_2 = out_2.squeeze(0)
    if numpy_type:
        out_2 = out_2.numpy()
        if not squeeze_flag:
            out_2 = out_2.transpose(1, 2, 0)

    return out_2


print(Random_array[0, :, :].shape)
result_2D = imresize(img=Random_array[0:1, :, :], scale=0.25, antialiasing=True)
print(result_2D)

In [25]:
# 验证自定义的imresize3d 与imresize函数对于三维数组的处理
from imgproc import imresize3D
import numpy as np
import math
import torch

np.random.seed(928)
arr3d_ = np.random.randint(1,10,size=(3, 12, 12)).astype(np.float32)
print(arr3d_)
resizeed_arr3d = imresize3D(img=arr3d_, scale=0.25, antialiasing=True)
print(resizeed_arr3d.shape)
print(resizeed_arr3d)


def cubic(x):
    """cubic function used for calculate_weights_indices."""
    absx = torch.abs(x)
    absx2 = absx**2
    absx3 = absx**3
    return (1.5 * absx3 - 2.5 * absx2 + 1) * (
        (absx <= 1).type_as(absx)) + (-0.5 * absx3 + 2.5 * absx2 - 4 * absx + 2) * (((absx > 1) *
                                                                                     (absx <= 2)).type_as(absx))


def calculate_weights_indices(in_length, out_length, scale, kernel, kernel_width, antialiasing):
    """Calculate weights and indices, used for imresize function.

    Args:
        in_length (int): Input length.
        out_length (int): Output length.
        scale (float): Scale factor.
        kernel_width (int): Kernel width.
        antialisaing (bool): Whether to apply anti-aliasing when downsampling.
    """

    if (scale < 1) and antialiasing:
        # Use a modified kernel (larger kernel width) to simultaneously
        # interpolate and antialias
        kernel_width = kernel_width / scale

    # Output-space coordinates
    x = torch.linspace(1, out_length, out_length)

    # Input-space coordinates. Calculate the inverse mapping such that 0.5
    # in output space maps to 0.5 in input space, and 0.5 + scale in output
    # space maps to 1.5 in input space.
    u = x / scale + 0.5 * (1 - 1 / scale)

    # What is the left-most pixel that can be involved in the computation?
    left = torch.floor(u - kernel_width / 2)

    # What is the maximum number of pixels that can be involved in the
    # computation?  Note: it's OK to use an extra pixel here; if the
    # corresponding weights are all zero, it will be eliminated at the end
    # of this function.
    p = math.ceil(kernel_width) + 2

    # The indices of the input pixels involved in computing the k-th output
    # pixel are in row k of the indices matrix.
    indices = left.view(out_length, 1).expand(out_length, p) + torch.linspace(0, p - 1, p).view(1, p).expand(
        out_length, p)

    # The weights used to compute the k-th output pixel are in row k of the
    # weights matrix.
    distance_to_center = u.view(out_length, 1).expand(out_length, p) - indices

    # apply cubic kernel
    if (scale < 1) and antialiasing:
        weights = scale * cubic(distance_to_center * scale)
    else:
        weights = cubic(distance_to_center)

    # Normalize the weights matrix so that each row sums to 1.
    weights_sum = torch.sum(weights, 1).view(out_length, 1)
    weights = weights / weights_sum.expand(out_length, p)

    # If a column in weights is all zero, get rid of it. only consider the
    # first and last column.
    weights_zero_tmp = torch.sum((weights == 0), 0)
    if not math.isclose(weights_zero_tmp[0], 0, rel_tol=1e-6):
        indices = indices.narrow(1, 1, p - 2)
        weights = weights.narrow(1, 1, p - 2)
    if not math.isclose(weights_zero_tmp[-1], 0, rel_tol=1e-6):
        indices = indices.narrow(1, 0, p - 2)
        weights = weights.narrow(1, 0, p - 2)
    weights = weights.contiguous()
    indices = indices.contiguous()
    sym_len_s = -indices.min() + 1
    sym_len_e = indices.max() - in_length
    indices = indices + sym_len_s - 1
    return weights, indices, int(sym_len_s), int(sym_len_e)


@torch.no_grad()
def imresize(img, scale, antialiasing=True):
    """imresize function same as MATLAB.

    It now only supports bicubic.
    The same scale applies for both height and width.

    Args:
        img (Tensor | Numpy array):
            Tensor: Input image with shape (c, h, w), [0, 1] range.
            Numpy: Input image with shape (h, w, c), [0, 1] range.
        scale (float): Scale factor. The same scale applies for both height
            and width.
        antialisaing (bool): Whether to apply anti-aliasing when downsampling.
            Default: True.

    Returns:
        Tensor: Output image with shape (c, h, w), [0, 1] range, w/o round.
    """
    squeeze_flag = False
    if type(img).__module__ == np.__name__:  # numpy type
        numpy_type = True
        if img.ndim == 2:
            img = img[:, :, None]
            squeeze_flag = True
        # img = torch.from_numpy(img).float()
        img = torch.from_numpy(img.transpose(2, 0, 1)).float()
    else:
        numpy_type = False
        if img.ndim == 2:
            img = img.unsqueeze(0)
            squeeze_flag = True

    in_c, in_h, in_w = img.size()
    # print(in_c, in_h, in_w)
    out_h, out_w = math.ceil(in_h * scale), math.ceil(in_w * scale)
    kernel_width = 4
    kernel = 'cubic'

    # get weights and indices
    weights_h, indices_h, sym_len_hs, sym_len_he = calculate_weights_indices(in_h, out_h, scale, kernel, kernel_width,
                                                                             antialiasing)
    weights_w, indices_w, sym_len_ws, sym_len_we = calculate_weights_indices(in_w, out_w, scale, kernel, kernel_width,
                                                                             antialiasing)
    # process H dimension
    # symmetric copying
    img_aug = torch.FloatTensor(in_c, in_h + sym_len_hs + sym_len_he, in_w)
    img_aug.narrow(1, sym_len_hs, in_h).copy_(img)

    sym_patch = img[:, :sym_len_hs, :]
    inv_idx = torch.arange(sym_patch.size(1) - 1, -1, -1).long()
    sym_patch_inv = sym_patch.index_select(1, inv_idx)
    img_aug.narrow(1, 0, sym_len_hs).copy_(sym_patch_inv)

    sym_patch = img[:, -sym_len_he:, :]
    inv_idx = torch.arange(sym_patch.size(1) - 1, -1, -1).long()
    sym_patch_inv = sym_patch.index_select(1, inv_idx)
    img_aug.narrow(1, sym_len_hs + in_h, sym_len_he).copy_(sym_patch_inv)

    out_1 = torch.FloatTensor(in_c, out_h, in_w)
    kernel_width = weights_h.size(1)
    for i in range(out_h):
        idx = int(indices_h[i][0])
        for j in range(in_c):
            out_1[j, i, :] = img_aug[j, idx:idx + kernel_width, :].transpose(0, 1).mv(weights_h[i])

    # process W dimension
    # symmetric copying
    out_1_aug = torch.FloatTensor(in_c, out_h, in_w + sym_len_ws + sym_len_we)
    out_1_aug.narrow(2, sym_len_ws, in_w).copy_(out_1)

    sym_patch = out_1[:, :, :sym_len_ws]
    inv_idx = torch.arange(sym_patch.size(2) - 1, -1, -1).long()
    sym_patch_inv = sym_patch.index_select(2, inv_idx)
    out_1_aug.narrow(2, 0, sym_len_ws).copy_(sym_patch_inv)

    sym_patch = out_1[:, :, -sym_len_we:]
    inv_idx = torch.arange(sym_patch.size(2) - 1, -1, -1).long()
    sym_patch_inv = sym_patch.index_select(2, inv_idx)
    out_1_aug.narrow(2, sym_len_ws + in_w, sym_len_we).copy_(sym_patch_inv)

    out_2 = torch.FloatTensor(in_c, out_h, out_w)
    kernel_width = weights_w.size(1)
    for i in range(out_w):
        idx = int(indices_w[i][0])
        for j in range(in_c):
            out_2[j, :, i] = out_1_aug[j, :, idx:idx + kernel_width].mv(weights_w[i])

    if squeeze_flag:
        out_2 = out_2.squeeze(0)
    if numpy_type:
        out_2 = out_2.numpy()
        if not squeeze_flag:
            out_2 = out_2.transpose(1, 2, 0)

    return out_2

print('[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[]]]]]]]]]]]]]]]]]]]]]]')
print(arr3d_.transpose(1, 2, 0).shape)
result = imresize(img=arr3d_.transpose(1, 2, 0), scale=0.25, antialiasing=True)
print(result)



[[[9. 4. 6. 4. 8. 7. 9. 8. 2. 9. 2. 8.]
  [2. 8. 1. 7. 9. 4. 3. 4. 8. 3. 9. 6.]
  [4. 8. 3. 7. 4. 1. 6. 4. 5. 8. 5. 9.]
  [9. 2. 9. 1. 2. 2. 2. 1. 8. 3. 9. 5.]
  [2. 1. 8. 1. 7. 3. 5. 3. 8. 7. 9. 1.]
  [9. 4. 2. 4. 2. 8. 9. 6. 6. 5. 4. 1.]
  [4. 7. 4. 5. 1. 2. 9. 4. 9. 2. 9. 4.]
  [7. 5. 7. 5. 9. 6. 9. 7. 2. 1. 5. 1.]
  [1. 3. 3. 8. 6. 7. 5. 9. 2. 3. 7. 3.]
  [2. 1. 9. 1. 1. 8. 9. 1. 7. 7. 4. 8.]
  [3. 6. 9. 2. 4. 8. 1. 4. 2. 7. 9. 6.]
  [8. 4. 6. 9. 5. 7. 6. 2. 5. 8. 7. 4.]]

 [[4. 6. 4. 4. 7. 8. 3. 4. 3. 7. 1. 8.]
  [7. 9. 2. 7. 7. 4. 7. 3. 6. 5. 9. 6.]
  [3. 2. 2. 9. 7. 4. 3. 7. 3. 9. 7. 7.]
  [9. 8. 1. 5. 5. 1. 8. 3. 3. 1. 9. 8.]
  [8. 7. 9. 4. 8. 4. 8. 7. 2. 5. 4. 3.]
  [2. 6. 8. 2. 5. 7. 5. 4. 5. 8. 7. 6.]
  [3. 1. 2. 8. 9. 3. 4. 8. 8. 9. 6. 5.]
  [8. 4. 6. 7. 2. 7. 7. 1. 1. 9. 8. 5.]
  [9. 2. 9. 6. 8. 5. 9. 3. 6. 6. 5. 8.]
  [9. 9. 7. 1. 8. 1. 7. 9. 7. 4. 5. 7.]
  [4. 1. 1. 2. 8. 6. 2. 4. 2. 7. 1. 7.]
  [7. 3. 4. 4. 9. 2. 4. 3. 8. 8. 3. 1.]]

 [[8. 1. 1. 5. 9. 9. 8. 8. 2. 6. 1. 

In [12]:
# 验证imresize函数对于三维数组的处理
import math
import numpy as np
import torch


def cubic(x):
    """cubic function used for calculate_weights_indices."""
    absx = torch.abs(x)
    absx2 = absx**2
    absx3 = absx**3
    return (1.5 * absx3 - 2.5 * absx2 + 1) * (
        (absx <= 1).type_as(absx)) + (-0.5 * absx3 + 2.5 * absx2 - 4 * absx + 2) * (((absx > 1) *
                                                                                     (absx <= 2)).type_as(absx))


def calculate_weights_indices(in_length, out_length, scale, kernel, kernel_width, antialiasing):
    """Calculate weights and indices, used for imresize function.

    Args:
        in_length (int): Input length.
        out_length (int): Output length.
        scale (float): Scale factor.
        kernel_width (int): Kernel width.
        antialisaing (bool): Whether to apply anti-aliasing when downsampling.
    """

    if (scale < 1) and antialiasing:
        # Use a modified kernel (larger kernel width) to simultaneously
        # interpolate and antialias
        kernel_width = kernel_width / scale

    # Output-space coordinates
    x = torch.linspace(1, out_length, out_length)

    # Input-space coordinates. Calculate the inverse mapping such that 0.5
    # in output space maps to 0.5 in input space, and 0.5 + scale in output
    # space maps to 1.5 in input space.
    u = x / scale + 0.5 * (1 - 1 / scale)

    # What is the left-most pixel that can be involved in the computation?
    left = torch.floor(u - kernel_width / 2)

    # What is the maximum number of pixels that can be involved in the
    # computation?  Note: it's OK to use an extra pixel here; if the
    # corresponding weights are all zero, it will be eliminated at the end
    # of this function.
    p = math.ceil(kernel_width) + 2

    # The indices of the input pixels involved in computing the k-th output
    # pixel are in row k of the indices matrix.
    indices = left.view(out_length, 1).expand(out_length, p) + torch.linspace(0, p - 1, p).view(1, p).expand(
        out_length, p)

    # The weights used to compute the k-th output pixel are in row k of the
    # weights matrix.
    distance_to_center = u.view(out_length, 1).expand(out_length, p) - indices

    # apply cubic kernel
    if (scale < 1) and antialiasing:
        weights = scale * cubic(distance_to_center * scale)
    else:
        weights = cubic(distance_to_center)

    # Normalize the weights matrix so that each row sums to 1.
    weights_sum = torch.sum(weights, 1).view(out_length, 1)
    weights = weights / weights_sum.expand(out_length, p)

    # If a column in weights is all zero, get rid of it. only consider the
    # first and last column.
    weights_zero_tmp = torch.sum((weights == 0), 0)
    if not math.isclose(weights_zero_tmp[0], 0, rel_tol=1e-6):
        indices = indices.narrow(1, 1, p - 2)
        weights = weights.narrow(1, 1, p - 2)
    if not math.isclose(weights_zero_tmp[-1], 0, rel_tol=1e-6):
        indices = indices.narrow(1, 0, p - 2)
        weights = weights.narrow(1, 0, p - 2)
    weights = weights.contiguous()
    indices = indices.contiguous()
    sym_len_s = -indices.min() + 1
    sym_len_e = indices.max() - in_length
    indices = indices + sym_len_s - 1
    return weights, indices, int(sym_len_s), int(sym_len_e)


@torch.no_grad()
def imresize(img, scale, antialiasing=True):
    """imresize function same as MATLAB.

    It now only supports bicubic.
    The same scale applies for both height and width.

    Args:
        img (Tensor | Numpy array):
            Tensor: Input image with shape (c, h, w), [0, 1] range.
            Numpy: Input image with shape (h, w, c), [0, 1] range.
        scale (float): Scale factor. The same scale applies for both height
            and width.
        antialisaing (bool): Whether to apply anti-aliasing when downsampling.
            Default: True.

    Returns:
        Tensor: Output image with shape (c, h, w), [0, 1] range, w/o round.
    """
    squeeze_flag = False
    if type(img).__module__ == np.__name__:  # numpy type
        numpy_type = True
        if img.ndim == 2:
            img = img[:, :, None]
            squeeze_flag = True
        img = torch.from_numpy(img.transpose(2, 0, 1)).float()
        # img = torch.from_numpy(img).float()
    else:
        numpy_type = False
        if img.ndim == 2:
            img = img.unsqueeze(0)
            squeeze_flag = True

    in_c, in_h, in_w = img.size()
    out_h, out_w = math.ceil(in_h * scale), math.ceil(in_w * scale)
    kernel_width = 4
    kernel = 'cubic'

    # get weights and indices
    weights_h, indices_h, sym_len_hs, sym_len_he = calculate_weights_indices(in_h, out_h, scale, kernel, kernel_width,
                                                                             antialiasing)
    weights_w, indices_w, sym_len_ws, sym_len_we = calculate_weights_indices(in_w, out_w, scale, kernel, kernel_width,
                                                                             antialiasing)
    # process H dimension
    # symmetric copying
    img_aug = torch.FloatTensor(in_c, in_h + sym_len_hs + sym_len_he, in_w)
    img_aug.narrow(1, sym_len_hs, in_h).copy_(img)

    sym_patch = img[:, :sym_len_hs, :]
    inv_idx = torch.arange(sym_patch.size(1) - 1, -1, -1).long()
    sym_patch_inv = sym_patch.index_select(1, inv_idx)
    img_aug.narrow(1, 0, sym_len_hs).copy_(sym_patch_inv)

    sym_patch = img[:, -sym_len_he:, :]
    inv_idx = torch.arange(sym_patch.size(1) - 1, -1, -1).long()
    sym_patch_inv = sym_patch.index_select(1, inv_idx)
    img_aug.narrow(1, sym_len_hs + in_h, sym_len_he).copy_(sym_patch_inv)

    out_1 = torch.FloatTensor(in_c, out_h, in_w)
    kernel_width = weights_h.size(1)
    for i in range(out_h):
        idx = int(indices_h[i][0])
        for j in range(in_c):
            out_1[j, i, :] = img_aug[j, idx:idx + kernel_width, :].transpose(0, 1).mv(weights_h[i])

    # process W dimension
    # symmetric copying
    out_1_aug = torch.FloatTensor(in_c, out_h, in_w + sym_len_ws + sym_len_we)
    out_1_aug.narrow(2, sym_len_ws, in_w).copy_(out_1)

    sym_patch = out_1[:, :, :sym_len_ws]
    inv_idx = torch.arange(sym_patch.size(2) - 1, -1, -1).long()
    sym_patch_inv = sym_patch.index_select(2, inv_idx)
    out_1_aug.narrow(2, 0, sym_len_ws).copy_(sym_patch_inv)

    sym_patch = out_1[:, :, -sym_len_we:]
    inv_idx = torch.arange(sym_patch.size(2) - 1, -1, -1).long()
    sym_patch_inv = sym_patch.index_select(2, inv_idx)
    out_1_aug.narrow(2, sym_len_ws + in_w, sym_len_we).copy_(sym_patch_inv)

    out_2 = torch.FloatTensor(in_c, out_h, out_w)
    kernel_width = weights_w.size(1)
    for i in range(out_w):
        idx = int(indices_w[i][0])
        for j in range(in_c):
            out_2[j, :, i] = out_1_aug[j, :, idx:idx + kernel_width].mv(weights_w[i])

    if squeeze_flag:
        out_2 = out_2.squeeze(0)
    if numpy_type:
        out_2 = out_2.numpy()
        if not squeeze_flag:
            out_2 = out_2.transpose(1, 2, 0)

    return out_2

# 随机生成一个二维numpy数组[16，16]
np.random.seed(928)
Random_array = np.random.randint(1,10,size=(3, 12, 12)).astype(np.float32)
print(Random_array)
# 对数组进行bicubic下采样
result = imresize(img=Random_array, scale=0.25, antialiasing=True)
print(result)

print(Random_array[0, :, :].shape)
result_2D = imresize(img=Random_array[0:1, :, :], scale=0.25, antialiasing=True)
print(result_2D)

[[[9. 4. 6. 4. 8. 7. 9. 8. 2. 9. 2. 8.]
  [2. 8. 1. 7. 9. 4. 3. 4. 8. 3. 9. 6.]
  [4. 8. 3. 7. 4. 1. 6. 4. 5. 8. 5. 9.]
  [9. 2. 9. 1. 2. 2. 2. 1. 8. 3. 9. 5.]
  [2. 1. 8. 1. 7. 3. 5. 3. 8. 7. 9. 1.]
  [9. 4. 2. 4. 2. 8. 9. 6. 6. 5. 4. 1.]
  [4. 7. 4. 5. 1. 2. 9. 4. 9. 2. 9. 4.]
  [7. 5. 7. 5. 9. 6. 9. 7. 2. 1. 5. 1.]
  [1. 3. 3. 8. 6. 7. 5. 9. 2. 3. 7. 3.]
  [2. 1. 9. 1. 1. 8. 9. 1. 7. 7. 4. 8.]
  [3. 6. 9. 2. 4. 8. 1. 4. 2. 7. 9. 6.]
  [8. 4. 6. 9. 5. 7. 6. 2. 5. 8. 7. 4.]]

 [[4. 6. 4. 4. 7. 8. 3. 4. 3. 7. 1. 8.]
  [7. 9. 2. 7. 7. 4. 7. 3. 6. 5. 9. 6.]
  [3. 2. 2. 9. 7. 4. 3. 7. 3. 9. 7. 7.]
  [9. 8. 1. 5. 5. 1. 8. 3. 3. 1. 9. 8.]
  [8. 7. 9. 4. 8. 4. 8. 7. 2. 5. 4. 3.]
  [2. 6. 8. 2. 5. 7. 5. 4. 5. 8. 7. 6.]
  [3. 1. 2. 8. 9. 3. 4. 8. 8. 9. 6. 5.]
  [8. 4. 6. 7. 2. 7. 7. 1. 1. 9. 8. 5.]
  [9. 2. 9. 6. 8. 5. 9. 3. 6. 6. 5. 8.]
  [9. 9. 7. 1. 8. 1. 7. 9. 7. 4. 5. 7.]
  [4. 1. 1. 2. 8. 6. 2. 4. 2. 7. 1. 7.]
  [7. 3. 4. 4. 9. 2. 4. 3. 8. 8. 3. 1.]]

 [[8. 1. 1. 5. 9. 9. 8. 8. 2. 6. 1. 

RuntimeError: The size of tensor a (6) must match the size of tensor b (3) at non-singleton dimension 1

In [2]:
# 验证BGR convert RGB的过程中shape是否变化
# BGR convert RGB
import cv2
import numpy as np

path = "D:\\OneDrive\\Pictures\\wallpaper\\Honkai  Star Rail Screenshot 2023.08.28 - 00.05.02.86.png"
gt_image = cv2.imread(path).astype(np.float32) / 255.
# gt_image = cv2.imread(path).astype(np.float32)
print(gt_image.shape)

# Show picture
cv2.imshow('Image', gt_image) 
cv2.waitKey(0)  
cv2.destroyAllWindows()

image_rgb = cv2.cvtColor(gt_image, cv2.COLOR_BGR2RGB)
print(image_rgb.shape)

# Show picture
cv2.imshow('image_rgb', image_rgb) 
cv2.waitKey(0)  
cv2.destroyAllWindows()

(1080, 1920, 3)
(1080, 1920, 3)


In [4]:
# 验证图片转换Ycbcr的过程中shape是否变化
import imgproc
image_rgb_tensor = imgproc.image_to_tensor(image_rgb, False, False)
print(image_rgb_tensor.shape)

image_rgb_tensor_batch = image_rgb_tensor.unsqueeze(0)
image_rgb_tensor_Y = imgproc.rgb_to_ycbcr_torch(image_rgb_tensor_batch, only_use_y_channel=True)
print(image_rgb_tensor_Y.shape)


torch.Size([3, 1080, 1920])
torch.Size([1, 1, 1080, 1920])


In [6]:
# 验证PSNR的计算
from image_quality_assessment import PSNR, SSIM
import cv2
import config
import imgproc
import core
import numpy as np

path = "D:\\OneDrive\\Pictures\\wallpaper\\Honkai  Star Rail Screenshot 2023.08.28 - 00.05.02.86.png"
gt_image = cv2.imread(path).astype(np.float32) / 255.
# gt_image = cv2.imread(path).astype(np.float32)
print(gt_image.shape)

gt_crop_tensor = imgproc.image_to_tensor(gt_image, False, False)
print(gt_crop_tensor.shape)

lr_flow_tensor = core.imresize(gt_crop_tensor,
                                                         scale=1 / 4,
                                                         antialiasing=True,
                                                         kernel='gaussian', sigma=1)

print(lr_flow_tensor.shape)

gt_flow_tensor = core.imresize(lr_flow_tensor,
                                                         scale=4,
                                                         antialiasing=True,
                                                         kernel='gaussian', sigma=1)
print(gt_flow_tensor.shape)
# Create an IQA evaluation model
psnr_model = PSNR(config.upscale_factor, config.only_test_y_channel)
ssim_model = SSIM(config.upscale_factor, config.only_test_y_channel)

gt_crop_tensor = gt_crop_tensor.unsqueeze(0)
gt_flow_tensor = gt_flow_tensor.unsqueeze(0)
psnr = psnr_model(gt_crop_tensor, gt_flow_tensor)
print(psnr)

(1080, 1920, 3)
torch.Size([3, 1080, 1920])
torch.Size([3, 270, 480])
torch.Size([3, 1080, 1920])
tensor([24.0486], dtype=torch.float64)


In [2]:
# 查看处理后的数据对
import numpy as np

path_val = 'D:\\Code\\PIV_dataset\\validate_lr\\PIV-2_00119.npy'

val_data = np.load(path_val)
print(val_data.shape)
print(val_data)

(3, 11, 5)
[[[0.48224375 0.50300002 0.46296632 0.38951027 0.36205029]
  [0.52098894 0.50204575 0.42975622 0.35610765 0.33768621]
  [0.52246904 0.47160119 0.38808197 0.33025241 0.32152754]
  [0.46634093 0.41360414 0.35357603 0.32408899 0.32167166]
  [0.40743607 0.3687045  0.34240526 0.34246466 0.34870413]
  [0.39235181 0.36830127 0.36028993 0.37218213 0.3850652 ]
  [0.392977   0.37778932 0.37411344 0.38428369 0.3953312 ]
  [0.37979832 0.37037039 0.37059009 0.37697873 0.37703335]
  [0.37448913 0.37293857 0.38045529 0.38557509 0.37696183]
  [0.37770957 0.38908762 0.4096756  0.41586491 0.39989519]
  [0.37209439 0.39596513 0.43104854 0.43840885 0.41244665]]

 [[0.41522995 0.42624071 0.41214654 0.42031074 0.44896662]
  [0.44854534 0.41984218 0.38408735 0.40902328 0.4594788 ]
  [0.47323248 0.39653334 0.34610355 0.40043017 0.48021877]
  [0.46478456 0.36214566 0.31579357 0.39781216 0.50092053]
  [0.4307802  0.32742652 0.29783046 0.39641634 0.51173258]
  [0.38989085 0.30096528 0.2908569  0.39434

In [13]:
# 查看处理后的数据对
import numpy as np
import torch
import core
from image_quality_assessment import PSNR, SSIM

path_val = 'D:\\Code\\PIV_dataset\\validate_lr\\PIV-2_00119.npy'

val_data_lr = np.load(path_val)
val_data_tensor_lr = torch.from_numpy(val_data_lr)

print(val_data_tensor_lr.shape)

val_data_tensor_sr = core.imresize(val_data_tensor_lr, scale=4, antialiasing=True)
print(val_data_tensor_sr.shape)

path_val_gt = 'D:\\Code\\PIV_dataset\\validate\\PIV-2_00119.npy'

val_data_gt = np.load(path_val_gt)
val_data_tensor_gt = torch.from_numpy(val_data_gt)
print(val_data_tensor_gt.shape)
print(val_data_tensor_gt)

# Create an IQA evaluation model
psnr_model = PSNR(config.upscale_factor, config.only_test_y_channel)
ssim_model = SSIM(config.upscale_factor, config.only_test_y_channel)

val_data_tensor_sr = val_data_tensor_sr.unsqueeze(0)
val_data_tensor_gt = val_data_tensor_gt.unsqueeze(0)
psnr = psnr_model(val_data_tensor_sr, val_data_tensor_gt)
print(psnr)

torch.Size([3, 11, 5])
torch.Size([3, 44, 20])
torch.Size([3, 44, 20])
tensor([[[-1.9186e-01, -2.8753e-01, -2.5524e-01,  ..., -2.7480e-02,
          -5.5208e-03,  3.5109e-02],
         [ 1.0065e-01,  9.6681e-02, -4.2623e-02,  ...,  1.9513e-01,
          -5.4763e-02,  1.3617e-01],
         [ 5.1280e-02,  4.3457e-02,  4.9578e-02,  ...,  6.4859e-02,
          -2.2632e-01,  7.9833e-02],
         ...,
         [-1.7835e-01, -1.4884e-01,  1.4378e-03,  ..., -1.0489e-01,
          -2.8079e-01, -6.0528e-02],
         [-4.2948e-03,  8.2635e-03, -8.5590e-02,  ...,  1.4834e-02,
          -3.5537e-01, -2.0080e-01],
         [-6.3229e-02, -2.4219e-01, -3.0746e-01,  ...,  1.5987e-02,
          -2.6113e-01,  2.8553e-02]],

        [[ 2.6903e-02, -4.2392e-03,  1.2745e-01,  ...,  9.3367e-01,
           5.2201e-01,  4.3816e-01],
         [-2.5793e-01, -3.9820e-02,  2.1605e-01,  ...,  9.2931e-01,
           3.8780e-01,  3.1465e-01],
         [ 4.9563e-02, -5.1602e-02,  2.6787e-01,  ...,  7.8299e-01,
     

In [5]:
import torch
import numpy as np

tensor_list2 = []
tensor_list = []
for j in range(6):
    for i in range(10):
        tensor_list.append(torch.rand((1, ), requires_grad=True))
    tensor_list2.append(tensor_list)
    tensor_list = []
print(tensor_list2)


# Convert tensor_list2 to a 2D NumPy array
numpy_array = np.array([[tensor.item() for tensor in row] for row in tensor_list2])

print(numpy_array)

[[tensor([0.0008], requires_grad=True), tensor([0.4823], requires_grad=True), tensor([0.6266], requires_grad=True), tensor([0.9953], requires_grad=True), tensor([0.9801], requires_grad=True), tensor([0.7133], requires_grad=True), tensor([0.3799], requires_grad=True), tensor([0.2258], requires_grad=True), tensor([0.2845], requires_grad=True), tensor([0.9372], requires_grad=True)], [tensor([0.4831], requires_grad=True), tensor([0.6777], requires_grad=True), tensor([0.3799], requires_grad=True), tensor([0.7434], requires_grad=True), tensor([0.0418], requires_grad=True), tensor([0.2852], requires_grad=True), tensor([0.2191], requires_grad=True), tensor([0.9256], requires_grad=True), tensor([0.6961], requires_grad=True), tensor([0.5950], requires_grad=True)], [tensor([0.5590], requires_grad=True), tensor([0.9199], requires_grad=True), tensor([0.0071], requires_grad=True), tensor([0.8158], requires_grad=True), tensor([0.5030], requires_grad=True), tensor([0.5611], requires_grad=True), tensor

In [ ]:
# 验证numpy的数组reshape的方式
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])

In [58]:
import numpy as np
import torch
np.random.seed(928)
# 随机生成一个三维numpy数组[5,6,3]
Random_array = np.random.randint(1,10,size=(5,4,3)).astype(np.float32)  
print(Random_array)

[[[9. 4. 6.]
  [4. 8. 7.]
  [9. 8. 2.]
  [9. 2. 8.]]

 [[2. 8. 1.]
  [7. 9. 4.]
  [3. 4. 8.]
  [3. 9. 6.]]

 [[4. 8. 3.]
  [7. 4. 1.]
  [6. 4. 5.]
  [8. 5. 9.]]

 [[9. 2. 9.]
  [1. 2. 2.]
  [2. 1. 8.]
  [3. 9. 5.]]

 [[2. 1. 8.]
  [1. 7. 3.]
  [5. 3. 8.]
  [7. 9. 1.]]]


In [59]:
Random_array[:, :, 2] = np.sqrt(Random_array[:, :, 0] ** 2 + Random_array[:, :, 1] ** 2, dtype=np.float32)
print(Random_array)

[[[ 9.         4.         9.848858 ]
  [ 4.         8.         8.944272 ]
  [ 9.         8.        12.0415945]
  [ 9.         2.         9.219544 ]]

 [[ 2.         8.         8.246211 ]
  [ 7.         9.        11.401754 ]
  [ 3.         4.         5.       ]
  [ 3.         9.         9.486833 ]]

 [[ 4.         8.         8.944272 ]
  [ 7.         4.         8.062258 ]
  [ 6.         4.         7.2111025]
  [ 8.         5.         9.433981 ]]

 [[ 9.         2.         9.219544 ]
  [ 1.         2.         2.236068 ]
  [ 2.         1.         2.236068 ]
  [ 3.         9.         9.486833 ]]

 [[ 2.         1.         2.236068 ]
  [ 1.         7.         7.071068 ]
  [ 5.         3.         5.8309517]
  [ 7.         9.        11.401754 ]]]


In [57]:
Random_array = Random_array[:, :, 2:3]
print(Random_array.shape)
sr_result_tensor = torch.from_numpy(np.ascontiguousarray(Random_array)).permute(2, 0, 1).float()
print(sr_result_tensor.shape)
print(sr_result_tensor)

(5, 4, 1)
torch.Size([1, 5, 4])
tensor([[[ 9.8489,  8.9443, 12.0416,  9.2195],
         [ 8.2462, 11.4018,  5.0000,  9.4868],
         [ 8.9443,  8.0623,  7.2111,  9.4340],
         [ 9.2195,  2.2361,  2.2361,  9.4868],
         [ 2.2361,  7.0711,  5.8310, 11.4018]]])


In [60]:
# other way
print(Random_array.shape)
sr_result_tensor = torch.from_numpy(np.ascontiguousarray(Random_array)).permute(2, 0, 1).float()
print(sr_result_tensor.shape)
print(sr_result_tensor[2:3, :, :])

(5, 4, 3)
torch.Size([3, 5, 4])
tensor([[[ 9.8489,  8.9443, 12.0416,  9.2195],
         [ 8.2462, 11.4018,  5.0000,  9.4868],
         [ 8.9443,  8.0623,  7.2111,  9.4340],
         [ 9.2195,  2.2361,  2.2361,  9.4868],
         [ 2.2361,  7.0711,  5.8310, 11.4018]]])


In [21]:
np.sqrt(Random_array[:, :, 0] ** 2 + Random_array[:, :, 1] ** 2)

array([[ 9.8488578 ,  8.94427191, 12.04159458,  9.21954446],
       [ 8.24621125, 11.40175425,  5.        ,  9.48683298],
       [ 8.94427191,  8.06225775,  7.21110255,  9.43398113],
       [ 9.21954446,  2.23606798,  2.23606798,  9.48683298],
       [ 2.23606798,  7.07106781,  5.83095189, 11.40175425]])

In [27]:
Random_array[:, :, 2].astype(np.float32)

array([[ 9.,  8., 12.,  9.],
       [ 8., 11.,  5.,  9.],
       [ 8.,  8.,  7.,  9.],
       [ 9.,  2.,  2.,  9.],
       [ 2.,  7.,  5., 11.]], dtype=float32)

In [11]:
np.sqrt(3 ** 2 + 4 ** 2)

5.0

In [38]:
A = np.array([[1,2,3],[4,5,6]]).astype(np.float32)  

print(np.sqrt(A[:, 0] ** 2 + A[:, 1] ** 2))
print(A[:, 2])
A[:, 2] = np.sqrt(A[:, 0] ** 2 + A[:, 1] ** 2).astype(np.float32)  
print(A)

[2.236068  6.4031243]
[3. 6.]
[[1.        2.        2.236068 ]
 [4.        5.        6.4031243]]


In [37]:
A = np.array([[1,2,3],[4,5,6]])

print(np.sqrt(A[:, 0] ** 2 + A[:, 1] ** 2))
print(A[:, 2])
A[:, 2] = np.sqrt(A[:, 0] ** 2 + A[:, 1] ** 2).astype(np.float32)  
print(A)

[2.23606798 6.40312424]
[3 6]
[[1 2 2]
 [4 5 6]]


In [63]:
import numpy as np
import torch
np.random.seed(928)
# 随机生成一个三维numpy数组[5,6,3]
array_01 = np.random.randint(1,10,size=(10,19,3)).astype(np.float32)  
max_value = np.max(array_01, axis=(0, 1))
print(max_value)
print(max_value[-1])

[9. 9. 9.]
9.0


In [5]:
import torch
def R_MAE(predicted, actual):
    absolute_error = torch.abs(predicted - actual)
    relative_error = absolute_error / torch.abs(actual + 1e-8)  # Adding a small epsilon to avoid division by zero
    loss = torch.mean(relative_error)
    return loss

tensor_pre = torch.rand((6, 5), requires_grad=True)
tensor_act = torch.rand((6, 5), requires_grad=True)

tensor_ = R_MAE(tensor_pre, tensor_act)
print(tensor_)

tensor(22.5763, grad_fn=<MeanBackward0>)


In [8]:
A = torch.tensor([[5.0,4,2], [1,0,6]])
print(torch.mean(A))
A[A == 0] = 100
print(A)

tensor(3.)
tensor([[  5.,   4.,   2.],
        [  1., 100.,   6.]])


In [2]:
import numpy as np
np.random.seed(9280)
# 随机生成一个三维numpy数组[5,6,3]
array_u_id = np.random.randint(1,10,size=(19,10)).astype(np.float32)  
array_u_id_idex = array_u_id[:, 0:5]
print(array_u_id_idex.shape)
u_mean = np.mean(array_u_id, axis=1)

u_mean_ex = np.expand_dims(u_mean, axis=1)

print(u_mean)
print(u_mean_ex)

(19, 5)
[5.6 4.8 5.3 5.7 4.8 5.1 5.7 3.8 5.4 5.4 5.6 4.2 6.2 4.8 4.  5.2 4.7 6.2
 4.9]
[[5.6]
 [4.8]
 [5.3]
 [5.7]
 [4.8]
 [5.1]
 [5.7]
 [3.8]
 [5.4]
 [5.4]
 [5.6]
 [4.2]
 [6.2]
 [4.8]
 [4. ]
 [5.2]
 [4.7]
 [6.2]
 [4.9]]


In [ ]:
import numpy as np  
  
# 加载.npy文件  
arr = np.load('F:\\PIV_export\\No_Heating\\center_blockage_0.7\\middle\\window_96_48_24\\model_data\\PIV_00001.npy')  

# 打印数组  
print(arr[0,:, 0])

In [2]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]]).astype(np.float32)
b = a ** 2
print(b)

[[ 1.  4.  9.]
 [16. 25. 36.]]
